# -*- coding: utf-8 -*-
"""
abmptools.cg.dpd.aij_io
-----------------------
fcews aij.dat (Python 辞書スクリプト形式) の読み書き。

aij.dat の正規形:

    # mode 'a' (Groot-Warren a パラメータ直接)
    aij = [['W', 'A', 55.0], ['W', 'W', 50.0], ['A', 'A', 50.0], ...]

    # mode 'chi' (Flory-Huggins χ → a に変換要)
    chi = [['A_Asp', 'B_Glu', -4.10838], ['A_Asp', 'C_Thr', -6.52812], ...]

dpdgen の `udfdpd_io.setupudfdpd` は両方を受け入れ、 chi 経由なら
``a_ij = aii + chi_ij / 0.306`` (= aii + 3.27·χ、 Groot-Warren) で変換する。
本モジュールも同じ振る舞いを再実装する。
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Tuple, Union

from .models import AijMatrix

logger = logging.getLogger(__name__)


def read_aij(path: Union[str, Path], aii: float = 25.0) -> AijMatrix:
    """aij.dat (Python script) を読み込んで :class:`AijMatrix` を返す。

    Parameters
    ----------
    path : str | Path
        aij.dat ファイルパス。
    aii : float, default 25.0
        chi モードからの a 変換時に使う同種粒子間 a。 calc_sett の `aii_val`
        が優先されるが、 standalone read 時は本引数を採用する。

    Returns
    -------
    AijMatrix
        mode は ``"a"`` (aij 定義) または ``"chi"`` (chi 定義) のいずれか。
        両方定義されている場合は ``"a"`` を優先 (dpdgen 互換)。

    Raises
    ------
    ValueError
        aij も chi も定義されていない場合。
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"aij file not found: {path}")

    aij_dic: Dict = {}
    code = path.read_text(encoding="utf-8")
    exec(code, aij_dic)  # noqa: S102 — Python 辞書スクリプト形式の信頼ファイル

    aij_raw = aij_dic.get("aij", [])
    chi_raw = aij_dic.get("chi", [])

    if aij_raw:
        pairs = [(str(x[0]), str(x[1]), float(x[2])) for x in aij_raw]
        mode = "a"
    elif chi_raw:
        pairs = [(str(x[0]), str(x[1]), float(x[2])) for x in chi_raw]
        mode = "chi"
    else:
        raise ValueError(
            f"neither 'aij' nor 'chi' found in {path} (mode 'a' / 'chi' のどちらか必須)"
        )

    # segments を pairs の登場順から抽出
    seen: Dict[str, None] = {}
    for a, b, _ in pairs:
        seen.setdefault(a, None)
        seen.setdefault(b, None)

    logger.info(
        "read_aij: %s pairs from %s (mode=%s, segments=%d)",
        len(pairs), path, mode, len(seen),
    )
    return AijMatrix(
        segments=list(seen.keys()),
        pairs=pairs,
        mode=mode,
        aii=aii,
    )


def write_aij(
    path: Union[str, Path],
    aij: AijMatrix,
    *,
    out_mode: str = "auto",
) -> None:
    """:class:`AijMatrix` を aij.dat (Python script) に書き出す。

    Parameters
    ----------
    path : str | Path
        出力先。
    aij : AijMatrix
        書き出す matrix。
    out_mode : str, default 'auto'
        - ``'auto'`` (既存挙動): ``aij.mode`` をそのまま使う。
        - ``'a'``: a 値で書き出す。 ``aij.mode='chi'`` なら ``to_a_values()`` で変換。
        - ``'chi'``: chi 値で書き出す。 ``aij.mode='a'`` なら ``to_chi_values()`` で
          逆変換 (Groot-Warren 逆向き、 G2)。
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if out_mode not in ("auto", "a", "chi"):
        raise ValueError(f"out_mode must be 'auto'/'a'/'chi', got {out_mode!r}")
    effective_mode = aij.mode if out_mode == "auto" else out_mode

    if effective_mode == "a":
        var_name = "aij"
        pairs = aij.to_a_values()
    else:
        var_name = "chi"
        pairs = aij.to_chi_values()

    lines = [
        "# fcews aij.dat (generated by abmptools.cg.dpd.aij_io)",
        f"# mode: {effective_mode}, aii: {aij.aii}, segments: {len(aij.segments)}",
    ]
    if effective_mode != aij.mode:
        lines.append(
            f"# converted from input mode={aij.mode!r} via Groot-Warren "
            f"(a = aii + chi/0.306, chi = (a-aii)*0.306)"
        )
    lines.append("")
    lines.append(f"{var_name} = [")
    for (i, j, v) in pairs:
        lines.append(f"    [{i!r}, {j!r}, {v}],")
    lines.append("]")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    logger.info(
        "write_aij: %d pairs -> %s (out_mode=%s, source_mode=%s)",
        len(pairs), path, effective_mode, aij.mode,
    )


def create_empty_aij(
    segments: List[str],
    *,
    aii: float = 25.0,
    mode: str = "a",
    off_diagonal: float = 25.0,
) -> AijMatrix:
    """全 segment ペア (i ≤ j) を含む :class:`AijMatrix` skeleton を生成する。

    aij.dat を hand-craft する際の出発点。 後で個別ペアの値を編集 (例えば
    cholesterol-water 疎水性 mismatch を設定) する想定。

    Parameters
    ----------
    segments : List[str]
        対象 segment 名のリスト (順序維持)。
    aii : float, default 25.0
        同種ペア (i==j) のデフォルト値。 a モードでは a パラメータ自体、 chi モードでは
        変換用 aii として持つ。
    mode : str, default 'a'
        ``'a'`` または ``'chi'``。 mode='chi' なら同種ペアは chi=0 で初期化、 他は 0。
    off_diagonal : float, default 25.0
        異種ペア (i!=j) のデフォルト値。 mode='a' なら a 値、 mode='chi' なら chi 値。

    Returns
    -------
    AijMatrix
        全 N*(N+1)/2 ペアを含む aij (同種は aii (mode='a') / 0 (mode='chi')、
        異種は off_diagonal)。

    Examples
    --------
    >>> from abmptools.cg.dpd import create_empty_aij, write_aij
    >>> aij = create_empty_aij(["A", "B", "W"], aii=25.0, off_diagonal=30.0)
    >>> write_aij("aij_skel.dat", aij)  # → hand-craft 用 skeleton

    Notes
    -----
    fcews の自動生成 aij.dat が使えない (FMO 計算未実施 / chi 値が手元にない) 場合の
    fallback として、 物理的合理性のある初期値で skeleton を作る用途。
    """
    if mode not in ("a", "chi"):
        raise ValueError(f"mode must be 'a' or 'chi', got {mode!r}")

    pairs: List[Tuple[str, str, float]] = []
    same_val = aii if mode == "a" else 0.0
    for i, si in enumerate(segments):
        pairs.append((si, si, same_val))
        for sj in segments[i + 1:]:
            pairs.append((si, sj, off_diagonal))

    logger.info(
        "create_empty_aij: %d segments → %d pairs (mode=%s, aii=%g, off-diagonal=%g)",
        len(segments), len(pairs), mode, aii, off_diagonal,
    )
    return AijMatrix(segments=list(segments), pairs=pairs, mode=mode, aii=aii)


def aij_to_dict(aij: AijMatrix) -> Dict[Tuple[str, str], float]:
    """対称 lookup 用に (seg_i, seg_j) → a value の辞書を構築。

    mode='chi' の場合は to_a_values() で変換済の値を使う。
    """
    a_values = aij.to_a_values()
    d: Dict[Tuple[str, str], float] = {}
    for (i, j, v) in a_values:
        d[(i, j)] = v
        d[(j, i)] = v
    return d
