# -*- coding: utf-8 -*-
"""
abmptools.cg.dpd.aij_io
-----------------------
fcews aij.dat (Python 辞書スクリプト形式) の読み書き。

aij.dat の正規形:

    # mode 'a' (Groot-Warren a パラメータ直接)
    aij = [['W', 'A', 55.0], ['W', 'W', 50.0], ['A', 'A', 50.0], ...]

    # mode 'chi' (Flory-Huggins χ → a に変換要)
    chi = [['A_Asp', 'B_Glu', -4.10838], ['A_Asp', 'C_Thr', -6.52812], ...]

dpdgen の `udfdpd_io.setupudfdpd` は両方を受け入れ、 chi 経由なら
``a_ij = aii + chi_ij / 0.306`` (= aii + 3.27·χ、 Groot-Warren) で変換する。
本モジュールも同じ振る舞いを再実装する。
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Tuple, Union

from .models import AijMatrix

logger = logging.getLogger(__name__)


def read_aij(path: Union[str, Path], aii: float = 25.0) -> AijMatrix:
    """aij.dat (Python script) を読み込んで :class:`AijMatrix` を返す。

    Parameters
    ----------
    path : str | Path
        aij.dat ファイルパス。
    aii : float, default 25.0
        chi モードからの a 変換時に使う同種粒子間 a。 calc_sett の `aii_val`
        が優先されるが、 standalone read 時は本引数を採用する。

    Returns
    -------
    AijMatrix
        mode は ``"a"`` (aij 定義) または ``"chi"`` (chi 定義) のいずれか。
        両方定義されている場合は ``"a"`` を優先 (dpdgen 互換)。

    Raises
    ------
    ValueError
        aij も chi も定義されていない場合。
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"aij file not found: {path}")

    aij_dic: Dict = {}
    code = path.read_text(encoding="utf-8")
    exec(code, aij_dic)  # noqa: S102 — Python 辞書スクリプト形式の信頼ファイル

    aij_raw = aij_dic.get("aij", [])
    chi_raw = aij_dic.get("chi", [])

    if aij_raw:
        pairs = [(str(x[0]), str(x[1]), float(x[2])) for x in aij_raw]
        mode = "a"
    elif chi_raw:
        pairs = [(str(x[0]), str(x[1]), float(x[2])) for x in chi_raw]
        mode = "chi"
    else:
        raise ValueError(
            f"neither 'aij' nor 'chi' found in {path} (mode 'a' / 'chi' のどちらか必須)"
        )

    # segments を pairs の登場順から抽出
    seen: Dict[str, None] = {}
    for a, b, _ in pairs:
        seen.setdefault(a, None)
        seen.setdefault(b, None)

    logger.info(
        "read_aij: %s pairs from %s (mode=%s, segments=%d)",
        len(pairs), path, mode, len(seen),
    )
    return AijMatrix(
        segments=list(seen.keys()),
        pairs=pairs,
        mode=mode,
        aii=aii,
    )


def write_aij(path: Union[str, Path], aij: AijMatrix) -> None:
    """:class:`AijMatrix` を aij.dat (Python script) に書き出す。

    Parameters
    ----------
    path : str | Path
        出力先。
    aij : AijMatrix
        書き出す matrix。 mode に応じて ``aij`` / ``chi`` のどちらの変数を書くか決まる。
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    var_name = aij.mode  # 'a' → 'aij' か 'chi' どちらかを書き出す
    if var_name == "a":
        var_name = "aij"

    lines = [
        "# fcews aij.dat (generated by abmptools.cg.dpd.aij_io)",
        f"# mode: {aij.mode}, aii: {aij.aii}, segments: {len(aij.segments)}",
        "",
        f"{var_name} = [",
    ]
    for (i, j, v) in aij.pairs:
        lines.append(f"    [{i!r}, {j!r}, {v}],")
    lines.append("]")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("write_aij: %d pairs -> %s (mode=%s)", len(aij.pairs), path, aij.mode)


def aij_to_dict(aij: AijMatrix) -> Dict[Tuple[str, str], float]:
    """対称 lookup 用に (seg_i, seg_j) → a value の辞書を構築。

    mode='chi' の場合は to_a_values() で変換済の値を使う。
    """
    a_values = aij.to_a_values()
    d: Dict[Tuple[str, str], float] = {}
    for (i, j, v) in a_values:
        d[(i, j)] = v
        d[(j, i)] = v
    return d
