# -*- coding: utf-8 -*-
"""
abmptools.crystal.job_templates
--------------------------------
HPC jobscript renderer for the crystal-FMO pipeline.

Four schedulers are supported:

- ``PJM``    -- Fugaku (RIKEN R-CCS) and other Fujitsu PRIMEHPC FX-series
- ``SLURM``  -- TSUBAME, ABCI, university HPC
- ``PBS``    -- legacy clusters running PBS Pro / Torque
- ``local``  -- plain ``bash`` invocation for small smoke runs

Each scheduler has a ``string.Template`` body. ``${name}`` in shell
contexts is escaped as ``$$name`` to avoid Python interpolation. The
PJM template mirrors the historical ``runab23q2_fgk.sh`` from the
csp7 sample (Fugaku, 12 nodes × 2 procs, OMP_NUM_THREADS=24).

Per-AJF scripts are produced by :func:`render_jobscript`. A batch
driver that loops over a sequence of AJF basenames is generated by
:func:`write_batch_runner` (mirrors the legacy
``createbatchrun.sh``).
"""
from __future__ import annotations

import os
from pathlib import Path
from string import Template
from typing import Iterable, List, Optional

from .models import HPCJobSpec


# ---------------------------------------------------------------------------
# Scheduler templates
#
# Notes on escaping:
# - Shell variable references such as ``$OMP_NUM_THREADS`` are written
#   as ``$$OMP_NUM_THREADS`` so ``string.Template.substitute`` keeps
#   them intact.
# - ``${...}`` shell expansions inside the body must likewise be
#   escaped as ``$${...}`` (see PJM ``${ABINIT_DIR}`` -> ``$${...}``).
# ---------------------------------------------------------------------------

PJM_TEMPLATE = Template("""#!/bin/bash

#------- pjsub option -------#
#PJM -L "rscgrp=${queue}"
#PJM -L "node=${nodes}"
#PJM --mpi "proc=${total_proc},max-proc-per-node=${proc_per_node}"
#PJM -L "elapse=${elapse}"
#PJM -g "${group}"
#PJM -j

module switch lang/tcsds-1.2.31

export OMP_NUM_THREADS=${omp_threads}
export OMP_STACKSIZE=256M

#------- Program execution -------#
${abinit_dir}/${mkinp} < ${ajf_name} > ${file_base}.inp
mpiexec -stdin ${file_base}.inp -stdout ${out_name} -stderr ${err_name} ${abinit_dir}/${binary_name}
""")


SLURM_TEMPLATE = Template("""#!/bin/bash
#SBATCH --partition=${queue}
#SBATCH --nodes=${nodes}
#SBATCH --ntasks-per-node=${proc_per_node}
#SBATCH --time=${elapse}
#SBATCH --job-name=${file_base}
#SBATCH --output=${out_name}
#SBATCH --error=${err_name}

export OMP_NUM_THREADS=${omp_threads}
export OMP_STACKSIZE=256M

${abinit_dir}/${mkinp} < ${ajf_name} > ${file_base}.inp
mpirun -np ${total_proc} ${abinit_dir}/${binary_name} < ${file_base}.inp
""")


PBS_TEMPLATE = Template("""#!/bin/bash
#PBS -q ${queue}
#PBS -l select=${nodes}:ncpus=${total_proc}:mpiprocs=${proc_per_node}
#PBS -l walltime=${elapse}
#PBS -N ${file_base}
#PBS -o ${out_name}
#PBS -e ${err_name}

cd $$PBS_O_WORKDIR

export OMP_NUM_THREADS=${omp_threads}
export OMP_STACKSIZE=256M

${abinit_dir}/${mkinp} < ${ajf_name} > ${file_base}.inp
mpirun -np ${total_proc} ${abinit_dir}/${binary_name} < ${file_base}.inp
""")


LOCAL_TEMPLATE = Template("""#!/bin/bash
# Local invocation (no scheduler). Suitable for `--run-local` smoke runs.
set -euo pipefail

export OMP_NUM_THREADS=${omp_threads}
export OMP_STACKSIZE=256M

${abinit_dir}/${mkinp} < ${ajf_name} > ${file_base}.inp
${abinit_dir}/${binary_name} < ${file_base}.inp > ${out_name} 2> ${err_name}
""")


_TEMPLATES = {
    "PJM": PJM_TEMPLATE,
    "SLURM": SLURM_TEMPLATE,
    "PBS": PBS_TEMPLATE,
    "local": LOCAL_TEMPLATE,
}


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------

def render_jobscript(spec: HPCJobSpec, ajf_path: str) -> str:
    """Render the jobscript text for one AJF input.

    Parameters
    ----------
    spec
        :class:`HPCJobSpec` from the build config.
    ajf_path
        AJF filename (basename or relative path). Used to derive
        ``file_base`` (without ``.ajf``) and the ``.log`` / ``.err``
        sibling names.

    Returns
    -------
    str
        Rendered shell script body. Caller is responsible for writing
        the file with executable bits set.
    """
    if spec.template_override is not None:
        tmpl = Template(Path(spec.template_override).read_text())
    else:
        tmpl = _TEMPLATES[spec.scheduler]

    file_base = os.path.splitext(os.path.basename(ajf_path))[0]
    suffix = f"_{spec.nodes}n-{spec.proc_per_node}p-{spec.omp_threads}t"
    out_name = f"{file_base}{suffix}.log"
    err_name = f"{file_base}{suffix}.err"
    total_proc = spec.nodes * spec.proc_per_node

    mkinp = (
        os.path.basename(spec.mkinp_path)
        if spec.mkinp_path
        else "mkinp_openver1rev20.py"
    )

    body = tmpl.substitute(
        queue=spec.queue,
        group=spec.group or "",
        nodes=spec.nodes,
        proc_per_node=spec.proc_per_node,
        total_proc=total_proc,
        omp_threads=spec.omp_threads,
        elapse=spec.elapse,
        abinit_dir=spec.abinit_dir,
        binary_name=spec.binary_name,
        mkinp=mkinp,
        ajf_name=os.path.basename(ajf_path),
        file_base=file_base,
        out_name=out_name,
        err_name=err_name,
    )

    if spec.extra_lines:
        body += "\n" + "\n".join(spec.extra_lines) + "\n"

    return body


# ---------------------------------------------------------------------------
# Batch runner (replaces createbatchrun.sh)
# ---------------------------------------------------------------------------

def write_batch_runner(
    ajf_paths: Iterable[str],
    output_dir: str,
    *,
    submit_command: Optional[str] = None,
) -> Path:
    """Emit a shell driver that submits each per-AJF jobscript in turn.

    Parameters
    ----------
    ajf_paths
        Iterable of AJF basenames (or relative paths). One submit line
        per entry.
    output_dir
        Directory to write ``runbatch.sh`` into.
    submit_command
        Submit command (``pjsub`` for PJM, ``sbatch`` for SLURM,
        ``qsub`` for PBS, or ``bash`` for local). If ``None``, the
        driver echoes the per-script names without submitting (dry
        run).

    Returns
    -------
    Path
        Absolute path to the written ``runbatch.sh``.
    """
    output_dir_path = Path(output_dir)
    output_dir_path.mkdir(parents=True, exist_ok=True)
    runner = output_dir_path / "runbatch.sh"

    lines: List[str] = ["#!/bin/bash", "set -euo pipefail", ""]
    for ajf in ajf_paths:
        base = os.path.splitext(os.path.basename(ajf))[0]
        script = f"{base}.sh"
        if submit_command:
            lines.append(f'{submit_command} "{script}"')
        else:
            lines.append(f'echo "would submit {script}"')

    runner.write_text("\n".join(lines) + "\n")
    runner.chmod(0o755)
    return runner


__all__ = [
    "render_jobscript",
    "write_batch_runner",
    "PJM_TEMPLATE",
    "SLURM_TEMPLATE",
    "PBS_TEMPLATE",
    "LOCAL_TEMPLATE",
]
