"""Regression tests: verify CLI output matches reference values.

Reference files were generated from:
- main branch (pre-refactor): generateajf, log2cpf, convertcpf
- pre-refactor commit (7cd75bf): udf2gro, gro2udf (udf+gro mode, from-top mode)
"""
import os
import re
import shutil
import subprocess
import sys

import pytest

TESTS_DIR = os.path.dirname(__file__)
REF_MAIN = os.path.join(TESTS_DIR, "regression", "reference", "main")
REF_PREREFACTOR = os.path.join(TESTS_DIR, "regression", "reference", "prerefactor")
SAMPLE_DIR = os.path.join(TESTS_DIR, os.pardir, "sample")


def _run(args, cwd):
    """Run a CLI command and return completed process."""
    return subprocess.run(
        [sys.executable, "-m"] + args,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=120,
    )


def _normalize_line(line):
    """Normalize lines that contain timestamps or absolute paths."""
    # CPF header: "... Generated by ABMPTools [log2cpf] 2026-04-05 00:54:50.125453"
    line = re.sub(
        r"(Generated by ABMPTools\b.*?)\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d+",
        r"\1 <TIMESTAMP>",
        line,
    )
    # TOP header: "; input: /tmp/.../test.udf"
    line = re.sub(r"^(;\s*input:\s+).*$", r"\1<PATH>", line)
    return line


def _compare_files(generated, reference, ignore_blank_lines=False):
    """Assert two files have identical content (ignoring timestamps/paths)."""
    with open(generated) as f:
        gen_lines = f.readlines()
    with open(reference) as f:
        ref_lines = f.readlines()
    if ignore_blank_lines:
        gen_lines = [l for l in gen_lines if l.strip()]
        ref_lines = [l for l in ref_lines if l.strip()]
    gen_text = "".join(_normalize_line(l) for l in gen_lines)
    ref_text = "".join(_normalize_line(l) for l in ref_lines)
    assert gen_text == ref_text, (
        f"Output differs from reference.\n"
        f"  generated: {generated}\n"
        f"  reference: {reference}\n"
    )


# ---------------------------------------------------------------------------
# generateajf: gly5.pdb with all method/option combinations
# ---------------------------------------------------------------------------
GENERATEAJF_PARAMS = [
    ("--method", "MP2D", "--resp", "--nonbo"),
    ("--method", "MP2D", "--resp"),
    ("--method", "MP2D", "--nonbo"),
    ("--method", "MP2D"),
    ("--method", "HF", "--resp", "--nonbo"),
    ("--method", "HF", "--resp"),
    ("--method", "HF", "--nonbo"),
    ("--method", "HF"),
    ("--method", "MP2"),
    ("--method", "MP3"),
    ("--method", "HF+D"),
    ("--nopieda", "-pb", "-bsse", "--method", "HF"),
    ("--nopieda", "-pb", "-bsse", "--method", "MP2"),
    ("--nopieda", "-pb", "-bsse", "--method", "MP3"),
    ("--nopieda", "-pb", "-bsse", "--method", "HF+D"),
    ("--nopieda", "-pb", "--method", "HF"),
    ("--nopieda", "-pb", "--method", "MP2"),
    ("--nopieda", "-pb", "--method", "MP3"),
    ("--nopieda", "-pb", "--method", "HF+D"),
    ("--nopieda", "-bsse", "--method", "HF"),
    ("--nopieda", "-bsse", "--method", "MP2"),
    ("--nopieda", "-bsse", "--method", "MP3"),
    ("--nopieda", "-bsse", "--method", "HF+D"),
    ("--nopieda", "--method", "HF"),
    ("--nopieda", "--method", "MP2"),
    ("--nopieda", "--method", "MP3"),
    ("--nopieda", "--method", "HF+D"),
    ("-pb", "-bsse", "--method", "HF"),
    ("-pb", "-bsse", "--method", "MP2"),
    ("-pb", "-bsse", "--method", "MP3"),
    ("-pb", "-bsse", "--method", "HF+D"),
    ("-pb", "--method", "HF"),
    ("-pb", "--method", "MP2"),
    ("-pb", "--method", "MP3"),
    ("-pb", "--method", "HF+D"),
    ("-bsse", "--method", "HF"),
    ("-bsse", "--method", "MP2"),
    ("-bsse", "--method", "MP3"),
    ("-bsse", "--method", "HF+D"),
    ("--method", "HF"),
    ("--method", "MP2"),
    ("--method", "MP3"),
    ("--method", "HF+D"),
]


def _ajf_id(params):
    """Create a short test ID from generateajf params."""
    return " ".join(params)


@pytest.mark.parametrize("extra_args", GENERATEAJF_PARAMS, ids=_ajf_id)
def test_generateajf_gly5(tmp_path, extra_args):
    """generateajf output must match main-branch reference."""
    pdb_src = os.path.join(SAMPLE_DIR, "generateajf", "gly5.pdb")
    shutil.copy(pdb_src, tmp_path / "gly5.pdb")

    result = _run(
        ["abmptools.generateajf", "-i", "gly5.pdb"] + list(extra_args),
        cwd=str(tmp_path),
    )
    assert result.returncode == 0, f"generateajf failed:\n{result.stderr}"

    # Find the generated .ajf file
    ajf_files = [f for f in os.listdir(tmp_path) if f.endswith(".ajf")]
    assert len(ajf_files) == 1, f"Expected 1 ajf, got {ajf_files}"
    ajf_name = ajf_files[0]

    ref_path = os.path.join(REF_MAIN, "generateajf_gly5", ajf_name)
    assert os.path.exists(ref_path), f"No reference file: {ref_path}"
    _compare_files(str(tmp_path / ajf_name), ref_path)


# ---------------------------------------------------------------------------
# log2cpf
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "log_file,cpf_file",
    [
        ("gly5-MP2-STO-3G-nbo.log", "gly5-MP2-STO-3G-nbo.cpf"),
        ("gly5-HF-STO-3G-resp.log", "gly5-HF-STO-3G-resp.cpf"),
    ],
)
def test_log2cpf(tmp_path, log_file, cpf_file):
    """log2cpf output must match main-branch reference."""
    src_dir = os.path.join(SAMPLE_DIR, "log2cpf")
    # Copy all needed files (log, ajf, pdb)
    for f in os.listdir(src_dir):
        src = os.path.join(src_dir, f)
        if os.path.isfile(src):
            shutil.copy(src, tmp_path / f)

    result = _run(
        ["abmptools.log2cpf", "-i", log_file, "-o", cpf_file],
        cwd=str(tmp_path),
    )
    assert result.returncode == 0, f"log2cpf failed:\n{result.stderr}"
    assert (tmp_path / cpf_file).exists()

    ref_path = os.path.join(REF_MAIN, "log2cpf", cpf_file)
    _compare_files(str(tmp_path / cpf_file), ref_path)


# ---------------------------------------------------------------------------
# convertcpf
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "in_cpf,out_cpf",
    [
        ("gly5-10.cpf", "gly5-10to23.cpf"),
        ("gly5-23.cpf", "gly5-23to23.cpf"),
        ("gly5-4201.cpf", "gly5-4to23.cpf"),
    ],
)
def test_convertcpf_gly5(tmp_path, in_cpf, out_cpf):
    """convertcpf output must match main-branch reference."""
    src_dir = os.path.join(SAMPLE_DIR, "convertcpf", "gly5")
    shutil.copy(os.path.join(src_dir, in_cpf), tmp_path / in_cpf)

    result = _run(
        ["abmptools.convertcpf", "-i", in_cpf, "-o", out_cpf],
        cwd=str(tmp_path),
    )
    assert result.returncode == 0, f"convertcpf failed:\n{result.stderr}"
    assert (tmp_path / out_cpf).exists()

    ref_path = os.path.join(REF_MAIN, "convertcpf_gly5", out_cpf)
    _compare_files(str(tmp_path / out_cpf), ref_path)


# ---------------------------------------------------------------------------
# udf2gro (added during refactor)
# ---------------------------------------------------------------------------
def test_udf2gro(tmp_path):
    """udf2gro output must match pre-refactor reference."""
    udf_src = os.path.join(SAMPLE_DIR, "udf2gro", "input", "test.udf")
    shutil.copy(udf_src, tmp_path / "test.udf")

    result = _run(
        ["abmptools.udf2gro", "test.udf", "test"],
        cwd=str(tmp_path),
    )
    assert result.returncode == 0, f"udf2gro failed:\n{result.stderr}"

    for ext in ("gro", "top", "mdp"):
        gen = str(tmp_path / f"test.{ext}")
        ref = os.path.join(REF_PREREFACTOR, "udf2gro", f"test.{ext}")
        assert os.path.exists(gen), f"Missing output: test.{ext}"
        _compare_files(gen, ref)


# ---------------------------------------------------------------------------
# gro2udf: udf + gro mode (added during refactor)
# ---------------------------------------------------------------------------
def test_gro2udf_udf_gro_mode(tmp_path):
    """gro2udf udf+gro mode output must match pre-refactor reference."""
    src_dir = os.path.join(SAMPLE_DIR, "gro2udf", "udf_and_gro_mode", "input")
    for f in os.listdir(src_dir):
        shutil.copy(os.path.join(src_dir, f), tmp_path / f)

    result = _run(
        ["abmptools.gro2udf", "test.udf", "output.gro"],
        cwd=str(tmp_path),
    )
    assert result.returncode == 0, f"gro2udf failed:\n{result.stderr}"

    gen = str(tmp_path / "test_groout.udf")
    ref = os.path.join(REF_PREREFACTOR, "gro2udf_udf_gro_mode", "test_groout.udf")
    assert os.path.exists(gen)
    _compare_files(gen, ref, ignore_blank_lines=True)


# ---------------------------------------------------------------------------
# gro2udf: --from-top mode (added during refactor)
# ---------------------------------------------------------------------------
def test_gro2udf_from_top_mode(tmp_path):
    """gro2udf --from-top mode output must match pre-refactor reference."""
    src_dir = os.path.join(SAMPLE_DIR, "gro2udf", "gro_top_mode", "input")
    for f in os.listdir(src_dir):
        shutil.copy(os.path.join(src_dir, f), tmp_path / f)

    result = _run(
        [
            "abmptools.gro2udf",
            "--from-top", "test.top", "output.gro",
            "--template", "template_empty.udf",
            "--out", "fromtop_out.udf",
        ],
        cwd=str(tmp_path),
    )
    assert result.returncode == 0, f"gro2udf --from-top failed:\n{result.stderr}"

    gen = str(tmp_path / "fromtop_out.udf")
    ref = os.path.join(REF_PREREFACTOR, "gro2udf_from_top_mode", "fromtop_out.udf")
    assert os.path.exists(gen)
    _compare_files(gen, ref, ignore_blank_lines=True)
