# -*- coding: utf-8 -*-
"""End-to-end formulation builder (7-stage pipeline)."""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from .mdp_templates import write_equilibration_mdps
from .models import FormulationBuildConfig, PeptideSpec
from .ndx import write_index_from_gro
from .packer import pack_cluster_templated, pack_mixed_solution
from .peptide_atomistic import (
    build_peptide_from_sequence,
    normalize_existing_pdb,
)
from .small_molecule import (
    SmallMoleculeResult,
    parameterize_small_molecule,
)
from .topology import TopologyArtifacts, build_topology
from ._subprocess import ensure_dir, write_text

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Multi-chain protein / disulfide helpers
# ---------------------------------------------------------------------------


def _parse_pdb_residue_map(pdb_path: str):
    """Parse a PDB and return ``(n_residues, {(chain, resid_int): cum_index})``.

    ``cum_index`` is the **1-based sequential residue position** in file
    order — exactly the residue index tleap assigns to ``sys.N`` after
    ``loadpdb`` (TER records do not create gaps). For a multi-chain peptide
    like insulin this yields A1..A21 → 1..21, B1..B30 → 22..51.
    """
    cum = 0
    mapping: Dict[Any, int] = {}
    prev_key = None
    for line in Path(pdb_path).read_text().splitlines():
        if not line.startswith(("ATOM", "HETATM")):
            continue
        chain = line[21]
        try:
            resid = int(line[22:26])
        except ValueError:
            continue
        key = (chain, resid)
        if key != prev_key:
            cum += 1
            mapping.setdefault(key, cum)
            prev_key = key
    return cum, mapping


def _rename_cys_to_cyx_in_pdb(pdb_path: str, residues) -> None:
    """Rename ``CYS`` → ``CYX`` (cols 18-20) for the given ``(chain, resid)``
    set, in-place. CYX is the ff14SB disulfide-bonded cysteine template
    (no SG thiol hydrogen), required before declaring the S-S bond in tleap.
    """
    want = set(residues)
    out: List[str] = []
    n_renamed = 0
    for line in Path(pdb_path).read_text().splitlines():
        if line.startswith(("ATOM", "HETATM")) and len(line) >= 26:
            chain = line[21]
            try:
                resid = int(line[22:26])
            except ValueError:
                resid = None
            resname = line[17:20].strip()
            if resname == "CYS" and (chain, resid) in want:
                padded = (line + " " * 80)[:80]
                lc = list(padded)
                lc[17:20] = list("CYX")
                line = "".join(lc).rstrip()
                n_renamed += 1
        out.append(line)
    if n_renamed:
        Path(pdb_path).write_text("\n".join(out) + "\n")
        logger.info(
            "Renamed %d Cys atom-records to CYX (disulfide) in %s",
            n_renamed, pdb_path,
        )


# ---------------------------------------------------------------------------
# Public artifact dataclass
# ---------------------------------------------------------------------------


@dataclass
class FormulationArtifacts:
    output_dir: str
    gro: str
    top: str
    ndx: str
    mdp_files: Dict[str, str]
    run_script: str
    config_json: str
    n_peptides_total: int
    atoms_estimate: int


# ---------------------------------------------------------------------------
# run.sh template
# ---------------------------------------------------------------------------


_RUN_SH_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by abmptools.formulation.builder
set -euo pipefail
cd "$(dirname "$0")"

GMX="${{GMX:-{gmx}}}"
NT="${{NT:-4}}"
export OMP_NUM_THREADS="$NT"
MDRUN_OPTS="${{MDRUN_OPTS:-}}"
MAXWARN="${{GROMPP_MAXWARN:-5}}"

TOP="system.top"
GRO0="system.gro"
NDX="system.ndx"

mkdir -p equil
"$GMX" grompp -f md/em.mdp -p "$TOP" -c "$GRO0" -n "$NDX" \\
    -o equil/em.tpr -po equil/em.mdp_out -maxwarn "$MAXWARN"
"$GMX" mdrun -deffnm equil/em -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

"$GMX" grompp -f md/nvt.mdp -p "$TOP" -c equil/em.gro -n "$NDX" \\
    -o equil/nvt.tpr -po equil/nvt.mdp_out -maxwarn "$MAXWARN"
"$GMX" mdrun -deffnm equil/nvt -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

"$GMX" grompp -f md/npt.mdp -p "$TOP" -c equil/nvt.gro -t equil/nvt.cpt \\
    -n "$NDX" -o equil/npt.tpr -po equil/npt.mdp_out -maxwarn "$MAXWARN"
"$GMX" mdrun -deffnm equil/npt -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

mkdir -p prod
"$GMX" grompp -f md/prod.mdp -p "$TOP" -c equil/npt.gro -t equil/npt.cpt \\
    -n "$NDX" -o prod/prod.tpr -po prod/prod.mdp_out -maxwarn "$MAXWARN"
"$GMX" mdrun -deffnm prod/prod -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

echo "=== prod complete ==="
"""


def render_run_script(*, gmx_path: str) -> str:
    return _RUN_SH_TEMPLATE.format(gmx=gmx_path)


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


class FormulationBuilder:
    """7-stage orchestrator for AA mixed-solution formulation builds."""

    def __init__(self, config: FormulationBuildConfig) -> None:
        self.config = config
        self.output_dir = Path(config.output_dir).resolve()

    # ------------------------------------------------------------------
    # Stage methods
    # ------------------------------------------------------------------

    def _stage0_ff_staging(self) -> Path:
        logger.info("=== Stage 0/7: ff staging ===")
        ensure_dir(self.output_dir)
        for sub in ("build", "build/input", "md", "analysis"):
            ensure_dir(self.output_dir / sub)
        return self.output_dir

    def _stage1_peptide_atomistic(self) -> List[Path]:
        logger.info("=== Stage 1/7: peptide atomistic ===")
        out_pdbs: List[Path] = []
        # GAFF-mode peptides are parameterised in stage 2 via acpype
        # (they share the small-molecule pipeline). Here we only need
        # to produce a clean input PDB.
        self._gaff_peptides: List[PeptideSpec] = []
        for pspec in self.config.system.peptides:
            target = self.output_dir / "build" / "input" / f"{pspec.name}.pdb"
            if pspec.parameterize_method == "gaff":
                # acpype enforces "only one residue" → rewrite all
                # resnames to pspec.resname (and all resnums to 1).
                normalize_existing_pdb(
                    src_pdb=pspec.pdb_path,
                    out_pdb=str(target),
                    strip_waters=True,
                    force_resname=pspec.resname,
                    force_resnum=1,
                )
                self._gaff_peptides.append(pspec)
            elif pspec.pdb_path:
                normalize_existing_pdb(
                    src_pdb=pspec.pdb_path,
                    out_pdb=str(target),
                    strip_waters=True,
                )
                # Disulfide-bonded Cys must be renamed CYS -> CYX so the
                # ff14SB template drops the SG thiol hydrogen (HG); the
                # actual S-S bond is then declared in the unified tleap
                # script (see _disulfide_tleap_bonds). Done on the
                # per-peptide PDB before packmol so every copy inherits CYX.
                if pspec.disulfide_bonds:
                    ss_residues = set()
                    for a_spec, b_spec in pspec.disulfide_bonds:
                        for spec in (a_spec, b_spec):
                            ch, rid, _atom = spec.split(":")
                            ss_residues.add((ch, int(rid)))
                    _rename_cys_to_cyx_in_pdb(str(target), ss_residues)
            else:
                # Render bond directives if disulfides declared.
                # disulfide_bond RESID is interpreted as a 1-based
                # position within the sequence; if cap_n is set, the
                # ACE cap adds 1 to every downstream residue's tleap
                # residue index. We apply that offset here so users
                # can specify ``("A:2:SG", "A:7:SG")`` in terms of
                # the sequence without minding the cap.
                cap_offset = 1 if pspec.cap_n else 0
                extra: List = []
                for a, b in pspec.disulfide_bonds:
                    a_parts = a.split(":")
                    b_parts = b.split(":")
                    a_resid = int(a_parts[1]) + cap_offset
                    b_resid = int(b_parts[1]) + cap_offset
                    a_resid_atom = f"{a_resid}.{a_parts[2]}"
                    b_resid_atom = f"{b_resid}.{b_parts[2]}"
                    extra.append((a_resid_atom, b_resid_atom))
                build_peptide_from_sequence(
                    sequence=pspec.sequence,
                    out_pdb=str(target),
                    workdir=str(self.output_dir / "build" / "tleap_peptide" / pspec.name),
                    tleap_path=self.config.tleap_path,
                    cap_n=pspec.cap_n,
                    cap_c=pspec.cap_c,
                    protein_leaprc=self.config.amber_protein_ff,
                    water_leaprc=self.config.amber_water_ff,
                    extra_bonds=extra,
                )
            out_pdbs.append(target)
        return out_pdbs

    def _stage2_small_mol_parameterize(self) -> List[SmallMoleculeResult]:
        logger.info("=== Stage 2/7: small molecule parameterize ===")
        results: List[SmallMoleculeResult] = []
        wd = self.output_dir / "build" / "input"
        # GAFF-mode peptides first (so tleap unified topology can
        # loadmol2 them as ligands in stage 4). Use Gasteiger charges
        # (``-c gas``) for whole-peptide parameterisation — AM1-BCC SCF
        # routinely fails to converge for >50-atom peptides, while
        # Gasteiger is empirical and always succeeds. Precision is
        # lower (charges within ~0.1e of AM1-BCC) but acceptable for
        # the qualitative aggregation/release questions this builder
        # is designed for.
        from ..genesis.mmgbsa.models import LigandParameterization
        self._gaff_peptide_results: List[SmallMoleculeResult] = []
        for pspec in getattr(self, "_gaff_peptides", []):
            src_pdb = wd / f"{pspec.name}.pdb"
            res = parameterize_small_molecule(
                name=f"{pspec.name}-gaff",
                resname=pspec.resname,
                pdb_path=str(src_pdb),
                net_charge=pspec.net_charge,
                workdir=wd,
                config=LigandParameterization(
                    charge_method="gas",
                    net_charge=pspec.net_charge,
                    atom_type="gaff2",
                    skip_if_cached=True,
                ),
                acpype_path=self.config.acpype_path,
            )
            self._gaff_peptide_results.append(res)
            results.append(res)
        for espec in self.config.system.enhancers:
            # Treat neutral and charged copies as distinct acpype runs.
            # Mangle the user-provided 3-letter resname into a 3-letter
            # unique tag per form: e.g. ``CPR`` → ``CPN`` (neutral) and
            # ``CPC`` (charged). tleap is strict about 3-char resnames,
            # so we shorten the user prefix to 2 chars and append N/C.
            base2 = espec.resname.strip()[:2].upper().ljust(2, "X")
            if espec.n_neutral > 0:
                res_n = parameterize_small_molecule(
                    name=f"{espec.name}-neutral",
                    resname=f"{base2}N",
                    smiles=espec.smiles_neutral,
                    pdb_path=espec.pdb_path_neutral,
                    net_charge=0,
                    workdir=wd,
                    acpype_path=self.config.acpype_path,
                )
                results.append(res_n)
            if espec.n_charged > 0:
                # Infer charge from SMILES (`[O-]` etc.) → user sets via spec.
                res_c = parameterize_small_molecule(
                    name=f"{espec.name}-charged",
                    resname=f"{base2}C",
                    smiles=espec.smiles_charged,
                    pdb_path=espec.pdb_path_charged,
                    net_charge=-1,  # fatty-acid / sulfonate default
                    workdir=wd,
                    acpype_path=self.config.acpype_path,
                )
                results.append(res_c)
        for bspec in self.config.system.bile_salts:
            if bspec.n_copies <= 0:
                continue
            res = parameterize_small_molecule(
                name=bspec.name,
                resname=bspec.resname,
                smiles=bspec.smiles,
                pdb_path=bspec.pdb_path,
                net_charge=bspec.net_charge,
                workdir=wd,
                acpype_path=self.config.acpype_path,
            )
            results.append(res)
        return results

    def _stage3_packmol(
        self,
        peptide_pdbs: List[Path],
        small_results: List[SmallMoleculeResult],
    ) -> Path:
        logger.info("=== Stage 3/7: packmol ===")
        component_pdbs: List[str] = []
        counts: List[int] = []
        # Peptide multi-copy. For GAFF-mode peptides we use the
        # acpype-rewritten PDB (``<resname>_NEW.pdb`` — same coords
        # but atom order + record type matching the mol2 atom types
        # so tleap loadpdb correctly maps to the loadmol2 template).
        gaff_results_by_name = {
            r.monomer_pdb.stem.replace("-gaff", "").replace("_atomistic", ""): r
            for r in getattr(self, "_gaff_peptide_results", [])
        }
        for pspec, pdb in zip(self.config.system.peptides, peptide_pdbs):
            if pspec.parameterize_method == "gaff":
                acp_new = (
                    self.output_dir / "build" / "input"
                    / f"{pspec.resname}.acpype" / f"{pspec.resname}_NEW.pdb"
                )
                if acp_new.is_file():
                    component_pdbs.append(str(acp_new))
                else:
                    # Fallback: pre-acpype monomer
                    gaff_pdb = self.output_dir / "build" / "input" / f"{pspec.resname}.pdb"
                    component_pdbs.append(str(gaff_pdb))
            else:
                component_pdbs.append(str(pdb))
            counts.append(pspec.n_copies)
        # Small molecule counts derived from spec
        smr_idx = 0
        # Skip GAFF peptide entries at the front of small_results
        smr_idx += len(getattr(self, "_gaff_peptide_results", []))
        for espec in self.config.system.enhancers:
            if espec.n_neutral > 0:
                component_pdbs.append(str(small_results[smr_idx].monomer_pdb))
                counts.append(espec.n_neutral)
                smr_idx += 1
            if espec.n_charged > 0:
                component_pdbs.append(str(small_results[smr_idx].monomer_pdb))
                counts.append(espec.n_charged)
                smr_idx += 1
        for bspec in self.config.system.bile_salts:
            if bspec.n_copies <= 0:
                continue
            component_pdbs.append(str(small_results[smr_idx].monomer_pdb))
            counts.append(bspec.n_copies)
            smr_idx += 1
        out_pdb = self.output_dir / "build" / "mixture.pdb"

        if self.config.system.packmol_layout == "cluster_core":
            # Partition component_pdbs / counts back into peptide /
            # enhancer / bile salt buckets in the same order the
            # builder created them.
            pep_pdbs = component_pdbs[: len(self.config.system.peptides)]
            pep_counts = counts[: len(self.config.system.peptides)]
            idx = len(self.config.system.peptides)
            enh_pdbs: List[str] = []
            enh_counts: List[int] = []
            for espec in self.config.system.enhancers:
                if espec.n_neutral > 0:
                    enh_pdbs.append(component_pdbs[idx])
                    enh_counts.append(counts[idx]); idx += 1
                if espec.n_charged > 0:
                    enh_pdbs.append(component_pdbs[idx])
                    enh_counts.append(counts[idx]); idx += 1
            bile_pdbs: List[str] = []
            bile_counts: List[int] = []
            for bspec in self.config.system.bile_salts:
                if bspec.n_copies <= 0:
                    continue
                bile_pdbs.append(component_pdbs[idx])
                bile_counts.append(counts[idx]); idx += 1
            pack_cluster_templated(
                peptide_pdbs=pep_pdbs, peptide_counts=pep_counts,
                enhancer_pdbs=enh_pdbs, enhancer_counts=enh_counts,
                bile_pdbs=bile_pdbs, bile_counts=bile_counts,
                box_size_nm=self.config.system.box_size_nm,
                out_pdb=str(out_pdb),
                core_radius_nm=self.config.system.cluster_core_radius_nm,
                shell_radius_nm=self.config.system.cluster_shell_radius_nm,
                tolerance_A=self.config.packmol_tolerance_A,
                inner_box_margin_nm=self.config.packmol_inner_box_margin_nm,
                seed=self.config.seed,
                packmol_path=self.config.packmol_path,
            )
        else:
            pack_mixed_solution(
                component_pdbs=component_pdbs,
                counts=counts,
                box_size_nm=self.config.system.box_size_nm,
                out_pdb=str(out_pdb),
                tolerance_A=self.config.packmol_tolerance_A,
                inner_box_margin_nm=self.config.packmol_inner_box_margin_nm,
                seed=self.config.seed,
                packmol_path=self.config.packmol_path,
            )
        return out_pdb

    def _stage4_solvate_ions(
        self,
        mixture_pdb: Path,
        small_results: List[SmallMoleculeResult],
    ) -> TopologyArtifacts:
        logger.info("=== Stage 4/7: solvate + ions (tleap unified) ===")
        extra_bonds = self._disulfide_tleap_bonds()
        if extra_bonds:
            logger.info(
                "Declaring %d disulfide bond(s) in unified tleap script.",
                len(extra_bonds),
            )
        return build_topology(
            config=self.config,
            mixture_pdb=str(mixture_pdb),
            small_molecules=small_results,
            workdir=str(self.output_dir / "build"),
            extra_bonds=extra_bonds or None,
        )

    def _disulfide_tleap_bonds(self) -> List[str]:
        """Compute ``bond sys.<i>.SG sys.<j>.SG`` directives for the unified
        tleap script, mapping each peptide's per-chain (chain, resid) Cys
        reference to its **global sequential residue index** in the loaded
        ``sys`` unit.

        Only applies to tleap-route peptides with ``pdb_path`` + declared
        ``disulfide_bonds``. The global index accounts for packmol writing
        peptides first (in config order), each repeated ``n_copies`` times,
        with multi-chain residues counted in PDB order (e.g. insulin
        A1..A21 then B1..B30 → cumulative 1..51).
        """
        directives: List[str] = []
        res_offset = 0  # sequential residue offset accumulated in packmol order
        for pspec in self.config.system.peptides:
            norm_pdb = self.output_dir / "build" / "input" / f"{pspec.name}.pdb"
            if not norm_pdb.is_file():
                continue
            n_res, resmap = _parse_pdb_residue_map(str(norm_pdb))
            ss_ok = (
                pspec.parameterize_method != "gaff"
                and pspec.pdb_path
                and pspec.disulfide_bonds
            )
            if ss_ok:
                for copy_i in range(pspec.n_copies):
                    copy_offset = res_offset + copy_i * n_res
                    for a_spec, b_spec in pspec.disulfide_bonds:
                        a_ch, a_rid, a_atom = a_spec.split(":")
                        b_ch, b_rid, b_atom = b_spec.split(":")
                        a_cum = resmap.get((a_ch, int(a_rid)))
                        b_cum = resmap.get((b_ch, int(b_rid)))
                        if a_cum is None or b_cum is None:
                            logger.warning(
                                "disulfide spec %s/%s not found in %s; "
                                "skipping.", a_spec, b_spec, norm_pdb,
                            )
                            continue
                        g_a = copy_offset + a_cum
                        g_b = copy_offset + b_cum
                        directives.append(
                            f"bond sys.{g_a}.{a_atom} sys.{g_b}.{b_atom}"
                        )
            res_offset += pspec.n_copies * n_res
        return directives

    def _stage5_index(self, top_art: TopologyArtifacts) -> Path:
        logger.info("=== Stage 5/7: index ===")
        ndx_path = self.output_dir / "system.ndx"
        enh = [e.resname for e in self.config.system.enhancers]
        # Account for the per-form resname mangling done in stage 2.
        enh_full: List[str] = []
        for e in self.config.system.enhancers:
            base2 = e.resname.strip()[:2].upper().ljust(2, "X")
            if e.n_neutral > 0:
                enh_full.append(f"{base2}N")
            if e.n_charged > 0:
                enh_full.append(f"{base2}C")
        bile = [b.resname for b in self.config.system.bile_salts]
        gaff_pep_resnames = [
            p.resname for p in self.config.system.peptides
            if p.parameterize_method == "gaff"
        ]
        write_index_from_gro(
            gro_path=top_art.gro,
            ndx_path=str(ndx_path),
            enhancer_resnames=enh_full or enh,
            bile_salt_resnames=bile,
            peptide_resnames=gaff_pep_resnames,
        )
        # Stage 4 emitted gro/top inside build/ — copy/link top + gro
        # next to the ndx so the run.sh sees system.{top,gro,ndx} flat.
        flat_top = self.output_dir / "system.top"
        flat_gro = self.output_dir / "system.gro"
        flat_top.write_text(Path(top_art.top).read_text())
        flat_gro.write_text(Path(top_art.gro).read_text())
        return ndx_path

    def _stage6_mdp_render(self) -> Dict[str, str]:
        logger.info("=== Stage 6/7: MDP render ===")
        restraint_text = ""
        if self.config.production.restraint_to_aggregate:
            # Auto-pick pbcatom for the Enhancer + Peptide groups from
            # the just-built system.ndx so the restraint pull block
            # doesn't trip the 0.5*half-box safety check.
            from .mdp_templates import render_aggregate_restraint_block
            from .umbrella_release import _find_median_atom_in_ndx_group
            ndx_path = self.output_dir / "system.ndx"
            try:
                pba1 = _find_median_atom_in_ndx_group(str(ndx_path), "Enhancer")
            except RuntimeError:
                pba1 = 0
            try:
                pba2 = _find_median_atom_in_ndx_group(str(ndx_path), "Peptide")
            except RuntimeError:
                pba2 = 0
            restraint_text = render_aggregate_restraint_block(
                k_kj_mol_nm2=self.config.production.restraint_k_kj_mol_nm2,
                pbcatom_group1=pba1,
                pbcatom_group2=pba2,
            )
        return write_equilibration_mdps(
            equilibration=self.config.equilibration,
            production=self.config.production,
            out_dir=str(self.output_dir / "md"),
            restraint_pull_text=restraint_text,
        )

    def _stage7_run_script(self) -> Path:
        logger.info("=== Stage 7/7: run script ===")
        run_path = self.output_dir / "run.sh"
        write_text(run_path, render_run_script(gmx_path=self.config.gmx_path))
        run_path.chmod(0o755)
        return run_path

    # ------------------------------------------------------------------
    # Public entry
    # ------------------------------------------------------------------

    def build(self) -> FormulationArtifacts:
        # Phase 1: force_field_route 切替 ('amber' | 'openff')
        route = getattr(self.config, "force_field_route", "amber")
        if route not in ("amber", "openff"):
            raise ValueError(
                f"force_field_route must be 'amber' or 'openff', got {route!r}"
            )

        self._stage0_ff_staging()

        # Snapshot config for reproducibility
        config_json = self.output_dir / "config.json"
        self.config.to_json(str(config_json))

        if route == "openff":
            return self._build_openff(config_json)

        # ---- Amber route (default、 Linux/macOS) ----
        peptide_pdbs = self._stage1_peptide_atomistic()
        small_results = self._stage2_small_mol_parameterize()
        mixture_pdb = self._stage3_packmol(peptide_pdbs, small_results)
        top_art = self._stage4_solvate_ions(mixture_pdb, small_results)
        ndx_path = self._stage5_index(top_art)
        mdp_files = self._stage6_mdp_render()
        run_path = self._stage7_run_script()

        # Estimate atom count from mixture + (rough) solvent shell
        atoms_est = self._estimate_atoms(top_art)
        n_pep = self.config.system.total_peptide_copies

        return FormulationArtifacts(
            output_dir=str(self.output_dir),
            gro=str(self.output_dir / "system.gro"),
            top=str(self.output_dir / "system.top"),
            ndx=str(ndx_path),
            mdp_files=mdp_files,
            run_script=str(run_path),
            config_json=str(config_json),
            n_peptides_total=n_pep,
            atoms_estimate=atoms_est,
        )

    def _build_openff(self, config_json: Path) -> FormulationArtifacts:
        """OpenFF route — Windows native (Phase 1).

        Stage 構成 (Amber route と差し替え):
            1. peptide_atomistic_openff: 既存 PDB → OpenFF Molecule + clean PDB
            2. small_molecule_openff:    SMILES → OpenFF Molecule + PDB
            3. packmol:                  Amber route と共有 (water は packmol で配置)
            4. topology_openff:          Interchange combine + GROMACS export
            5-7: Amber route と共有 (ndx / mdp / run script)

        Phase 1 制限: peptide は ``PeptideSpec.pdb_path`` 必須 (sequence
        から build は Phase 2)。 water + ions は packmol stage で配置済前提。
        """
        from .peptide_atomistic_openff import (
            PeptideOpenFFResult,
            build_peptide_openff,
        )
        from .small_molecule_openff import (
            SmallMoleculeOpenFFResult,
            parameterize_small_mol_openff,
        )
        from .topology_openff import (
            export_gromacs_files,
            merge_to_interchange,
            solvate_and_neutralize_gmx,
        )

        build_dir = self.output_dir / "build"

        # Stage 1: peptide (OpenFF route)
        logger.info("=== Stage 1/7 (OpenFF): peptide ===")
        peptide_results: List[PeptideOpenFFResult] = []
        for pspec in self.config.system.peptides:
            r = build_peptide_openff(
                spec=pspec, output_dir=build_dir / "input",
            )
            peptide_results.append(r)

        # Stage 2: small molecules (caprate × 2 + bile salt)
        logger.info("=== Stage 2/7 (OpenFF): small molecules ===")
        sm_results: List[SmallMoleculeOpenFFResult] = []
        for espec in self.config.system.enhancers:
            if espec.smiles_neutral and espec.n_neutral > 0:
                sm_results.append(parameterize_small_mol_openff(
                    smiles=espec.smiles_neutral,
                    resname=espec.resname,
                    net_charge=0,
                    output_dir=build_dir / "input",
                ))
            if espec.smiles_charged and espec.n_charged > 0:
                sm_results.append(parameterize_small_mol_openff(
                    smiles=espec.smiles_charged,
                    resname=f"{espec.resname[:2]}C"[:3],
                    net_charge=-1,
                    output_dir=build_dir / "input",
                ))
        for bspec in self.config.system.bile_salts:
            sm_results.append(parameterize_small_mol_openff(
                smiles=bspec.smiles,
                resname=bspec.resname,
                net_charge=bspec.net_charge,
                output_dir=build_dir / "input",
            ))

        # Phase 2-A: water 1 個を typing template として追加
        # (Interchange の SMIRNOFF stack に tip3p.offxml を含めることで
        # system.top に water moltype が登録される。 後段 gmx solvate で
        # 本番量に増やす。)
        water_template = parameterize_small_mol_openff(
            smiles="O",
            resname="HOH",
            net_charge=0,
            output_dir=build_dir / "input",
            charge_method="gasteiger",  # TIP3P SMIRNOFF が charge を override
        )
        sm_results.append(water_template)

        # Stage 3: packmol (OpenFF 専用、 water 1 個も含める)
        logger.info("=== Stage 3/7 (OpenFF): packmol (with water template) ===")
        from ..amorphous.packing import run_packmol

        peptide_pdbs = [r.pdb_path for r in peptide_results]
        component_pdbs: List[str] = [str(p) for p in peptide_pdbs]
        counts: List[int] = [p.n_copies for p in self.config.system.peptides]
        for r in sm_results:
            component_pdbs.append(str(r.pdb_path))
        counts.extend(self._enhancer_counts_for_openff())
        counts.extend([b.n_copies for b in self.config.system.bile_salts])
        counts.append(1)  # water template (Phase 2-A)

        mixture_pdb = run_packmol(
            pdb_paths=component_pdbs,
            counts=counts,
            box_size_nm=self.config.system.box_size_nm
                * (1 - self.config.packmol_inner_box_margin_nm / self.config.system.box_size_nm),
            output_pdb=str(build_dir / "mixture.pdb"),
            build_dir=str(build_dir),
            tolerance=self.config.packmol_tolerance_A,
            seed=self.config.seed,
            packmol_path=self.config.packmol_path,
        )
        mixture_pdb = Path(mixture_pdb)

        # Stage 4: topology (Interchange + GROMACS export, OpenFF route)
        logger.info("=== Stage 4/7 (OpenFF): topology (Interchange) ===")
        # 順序: peptide × N + enhancer (neu, chg) + bile salt の順を維持
        species_mols = [r.molecule for r in peptide_results] + [r.molecule for r in sm_results]
        species_counts = (
            [p.n_copies for p in self.config.system.peptides]
            + [c for c in self._enhancer_counts_for_openff()]
            + [b.n_copies for b in self.config.system.bile_salts]
            + [1]  # water template (Phase 2-A、 gmx solvate で増やす)
        )
        ic = merge_to_interchange(
            species_molecules=species_mols,
            species_counts=species_counts,
            mixture_pdb=mixture_pdb,
            box_size_nm=self.config.system.box_size_nm,
            use_precomputed_charges=True,
        )
        top_result = export_gromacs_files(
            interchange=ic,
            gro_path=self.output_dir / "system.gro",
            top_path=self.output_dir / "system.top",
        )

        # Phase 2-A: gmx solvate + genion で wet system に拡張
        if self.config.system.neutralize:
            logger.info("=== Stage 4.5/7 (OpenFF Phase 2-A): solvate + neutralize via gmx ===")
            try:
                top_result = solvate_and_neutralize_gmx(
                    gro_path=top_result.gro_path,
                    top_path=top_result.top_path,
                    box_size_nm=self.config.system.box_size_nm,
                    salt_concentration_M=self.config.system.salt_concentration_M,
                    gmx=self.config.gmx_path,
                    workdir=build_dir,
                )
            except RuntimeError as exc:
                logger.warning(
                    "Phase 2-A solvate skipped (%s). "
                    "Output is dry-mixed; add water/ions manually via "
                    "`gmx solvate` + `gmx genion` if needed.", exc,
                )

        # Stage 5-7: shared with Amber route (ndx writer は top_art を期待)。
        # Amber route の TopologyArtifacts は prmtop/inpcrd/tleap_input/tleap_log
        # を持つが、 OpenFF route はそれらを生成しない。 ``_stage5_index`` が読む
        # のは ``gro`` と ``top`` のみなので、 残り field は空文字で埋める。
        top_art = TopologyArtifacts(
            prmtop="",
            inpcrd="",
            top=str(top_result.top_path),
            gro=str(top_result.gro_path),
            tleap_input="",
            tleap_log="",
        )
        ndx_path = self._stage5_index(top_art)
        mdp_files = self._stage6_mdp_render()
        run_path = self._stage7_run_script()

        n_pep = self.config.system.total_peptide_copies
        return FormulationArtifacts(
            output_dir=str(self.output_dir),
            gro=str(top_result.gro_path),
            top=str(top_result.top_path),
            ndx=str(ndx_path),
            mdp_files=mdp_files,
            run_script=str(run_path),
            config_json=str(config_json),
            n_peptides_total=n_pep,
            atoms_estimate=top_result.n_atoms_total,
        )

    def _enhancer_counts_for_openff(self) -> List[int]:
        """OpenFF route の species 順序に合わせて enhancer counts を flatten."""
        out: List[int] = []
        for espec in self.config.system.enhancers:
            if espec.smiles_neutral and espec.n_neutral > 0:
                out.append(espec.n_neutral)
            if espec.smiles_charged and espec.n_charged > 0:
                out.append(espec.n_charged)
        return out

    @staticmethod
    def _estimate_atoms(top_art: TopologyArtifacts) -> int:
        gro = Path(top_art.gro)
        if not gro.is_file():
            return 0
        with gro.open() as f:
            f.readline()
            return int(f.readline().strip().split()[0])


class _SmallMolShim:
    """Adapter to feed :class:`SmallMoleculeOpenFFResult` into the shared
    Amber-route ``_stage3_packmol`` (which only reads ``.monomer_pdb``).
    """

    __slots__ = ("monomer_pdb",)

    def __init__(self, openff_result) -> None:
        self.monomer_pdb = openff_result.pdb_path


__all__ = [
    "FormulationArtifacts",
    "FormulationBuilder",
    "render_run_script",
]
