# -*- coding: utf-8 -*-
"""MDP file writers for the formulation builder.

Protocol (Hossain et al. 2023):
- em:  steepest descent, emtol 1000 kJ/mol/nm, 10 000 steps
- nvt: V-rescale 310 K, 100 ps, 2-group thermostat
       (Peptide_Solute vs. (Solvent ∪ Ions))
- npt: c-rescale 1 bar (eq) / Parrinello-Rahman 1 bar (prod), isotropic
- VdW: force-switch 1.0 → 1.2 nm; PME 1.2 nm cutoff
- dt:  2 fs with H-LINCS constraints
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, Optional

from .models import EquilibrationProtocol, ProductionProtocol

logger = logging.getLogger(__name__)


# Two-group thermostat naming (kept here so callers don't have to keep
# remembering the convention)
DEFAULT_TC_GROUPS = ("Peptide_Solute", "Non_Peptide")


def _strip(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.strip("\n").splitlines()) + "\n"


def render_em_mdp(*, equilibration: EquilibrationProtocol) -> str:
    em = f"""
; Auto-generated by abmptools.formulation.mdp_templates.render_em_mdp
integrator               = steep
emtol                    = {equilibration.em_tol}
emstep                   = 0.01
nsteps                   = {equilibration.em_steps}

nstlist                  = 10
cutoff-scheme            = Verlet
ns_type                  = grid
coulombtype              = PME
rcoulomb                 = 1.2
vdwtype                  = Cut-off
vdw-modifier             = Force-switch
rvdw-switch              = 1.0
rvdw                     = 1.2

constraints              = none
pbc                      = xyz
"""
    return _strip(em)


def render_nvt_mdp(
    *, equilibration: EquilibrationProtocol,
    tc_groups: Optional[tuple] = None,
) -> str:
    g1, g2 = tc_groups or DEFAULT_TC_GROUPS
    nvt = f"""
; Auto-generated by abmptools.formulation.mdp_templates.render_nvt_mdp
integrator               = md
dt                       = {equilibration.dt_ps}
nsteps                   = {equilibration.nvt_nsteps}

nstxout-compressed       = {equilibration.nstxout_compressed}
nstenergy                = {equilibration.nstenergy}
nstlog                   = {equilibration.nstenergy}

cutoff-scheme            = Verlet
nstlist                  = 20
coulombtype              = PME
rcoulomb                 = 1.2
vdwtype                  = Cut-off
vdw-modifier             = Force-switch
rvdw-switch              = 1.0
rvdw                     = 1.2

tcoupl                   = V-rescale
tc-grps                  = {g1} {g2}
tau_t                    = {equilibration.tau_t_ps} {equilibration.tau_t_ps}
ref_t                    = {equilibration.temperature_K} {equilibration.temperature_K}

pcoupl                   = no

gen_vel                  = yes
gen_temp                 = {equilibration.temperature_K}
gen_seed                 = {equilibration.gen_seed if equilibration.gen_seed is not None else -1}

constraints              = h-bonds
constraint-algorithm     = LINCS
lincs-iter               = 1
lincs-order              = 4
"""
    return _strip(nvt)


def render_npt_eq_mdp(
    *, equilibration: EquilibrationProtocol,
    tc_groups: Optional[tuple] = None,
) -> str:
    """Equilibration NPT — c-rescale Pcoupl (gentle), isotropic."""
    g1, g2 = tc_groups or DEFAULT_TC_GROUPS
    npt = f"""
; Auto-generated by abmptools.formulation.mdp_templates.render_npt_eq_mdp
integrator               = md
dt                       = {equilibration.dt_ps}
nsteps                   = {equilibration.npt_nsteps}

nstxout-compressed       = {equilibration.nstxout_compressed}
nstenergy                = {equilibration.nstenergy}
nstlog                   = {equilibration.nstenergy}

cutoff-scheme            = Verlet
nstlist                  = 20
coulombtype              = PME
rcoulomb                 = 1.2
vdwtype                  = Cut-off
vdw-modifier             = Force-switch
rvdw-switch              = 1.0
rvdw                     = 1.2

tcoupl                   = V-rescale
tc-grps                  = {g1} {g2}
tau_t                    = {equilibration.tau_t_ps} {equilibration.tau_t_ps}
ref_t                    = {equilibration.temperature_K} {equilibration.temperature_K}

pcoupl                   = c-rescale
pcoupltype               = isotropic
tau_p                    = {equilibration.tau_p_ps}
ref_p                    = {equilibration.pressure_bar}
compressibility          = {equilibration.compressibility}

gen_vel                  = no

constraints              = h-bonds
constraint-algorithm     = LINCS
lincs-iter               = 1
lincs-order              = 4
"""
    return _strip(npt)


def render_production_mdp(
    *, production: ProductionProtocol,
    tc_groups: Optional[tuple] = None,
) -> str:
    """Production NPT — Parrinello-Rahman, isotropic (Hossain protocol)."""
    g1, g2 = tc_groups or DEFAULT_TC_GROUPS
    prod = f"""
; Auto-generated by abmptools.formulation.mdp_templates.render_production_mdp
integrator               = md
dt                       = {production.dt_ps}
nsteps                   = {production.nsteps}

nstxout-compressed       = {production.nstxout_compressed}
nstenergy                = {production.nstenergy}
nstlog                   = {production.nstenergy}

cutoff-scheme            = Verlet
nstlist                  = 20
coulombtype              = PME
rcoulomb                 = 1.2
vdwtype                  = Cut-off
vdw-modifier             = Force-switch
rvdw-switch              = 1.0
rvdw                     = 1.2

tcoupl                   = V-rescale
tc-grps                  = {g1} {g2}
tau_t                    = {production.tau_t_ps} {production.tau_t_ps}
ref_t                    = {production.temperature_K} {production.temperature_K}

pcoupl                   = Parrinello-Rahman
pcoupltype               = isotropic
tau_p                    = {production.tau_p_ps}
ref_p                    = {production.pressure_bar}
compressibility          = {production.compressibility}

gen_vel                  = no

constraints              = h-bonds
constraint-algorithm     = LINCS
lincs-iter               = 1
lincs-order              = 4
"""
    return _strip(prod)


def write_equilibration_mdps(
    *,
    equilibration: EquilibrationProtocol,
    production: ProductionProtocol,
    out_dir: str,
    tc_groups: Optional[tuple] = None,
) -> Dict[str, str]:
    """Render and write em/nvt/npt/prod MDPs."""
    od = Path(out_dir).resolve()
    od.mkdir(parents=True, exist_ok=True)
    paths = {
        "em":   str(od / "em.mdp"),
        "nvt":  str(od / "nvt.mdp"),
        "npt":  str(od / "npt.mdp"),
        "prod": str(od / "prod.mdp"),
    }
    Path(paths["em"]).write_text(render_em_mdp(equilibration=equilibration))
    Path(paths["nvt"]).write_text(
        render_nvt_mdp(equilibration=equilibration, tc_groups=tc_groups)
    )
    Path(paths["npt"]).write_text(
        render_npt_eq_mdp(equilibration=equilibration, tc_groups=tc_groups)
    )
    Path(paths["prod"]).write_text(
        render_production_mdp(production=production, tc_groups=tc_groups)
    )
    logger.info("formulation MDPs written: %s", list(paths.values()))
    return paths
