# -*- coding: utf-8 -*-
"""Build a single-copy peptide PDB ready for packmol.

Two routes:

1. ``sequence`` → tleap with ``leaprc.protein.ff14SB`` builds a linear
   peptide; we then capture the saved PDB with the requested caps
   (ACE/NME via tleap's standard residue library).
2. ``pdb_path`` → use the user-supplied PDB as-is, with light cleanup
   (strip CRYST1/CONECT, normalise resnames).

Multi-copy replication is handled by packmol (``counts=n_copies`` in
the packer), so this module always returns a one-molecule PDB.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import List, Optional, Tuple

from ._subprocess import CommandError, ensure_dir, run_command, write_text

logger = logging.getLogger(__name__)


ONE_LETTER_TO_THREE = {
    "A": "ALA", "R": "ARG", "N": "ASN", "D": "ASP", "C": "CYS",
    "Q": "GLN", "E": "GLU", "G": "GLY", "H": "HIS", "I": "ILE",
    "L": "LEU", "K": "LYS", "M": "MET", "F": "PHE", "P": "PRO",
    "S": "SER", "T": "THR", "W": "TRP", "Y": "TYR", "V": "VAL",
}


def sequence_to_tleap_residues(
    sequence: str,
    *,
    cap_n: str = "",
    cap_c: str = "",
) -> str:
    """Return a tleap residue list string e.g. ``{ACE ALA ALA NME}``."""
    seq = sequence.strip().upper()
    bad = [c for c in seq if c not in ONE_LETTER_TO_THREE]
    if bad:
        raise ValueError(
            f"sequence contains non-natural one-letter codes: {bad!r}"
        )
    res = [ONE_LETTER_TO_THREE[c] for c in seq]
    if cap_n:
        res = [cap_n] + res
    if cap_c:
        res = res + [cap_c]
    return "{ " + " ".join(res) + " }"


def render_tleap_input_from_sequence(
    *,
    sequence: str,
    out_pdb: str,
    cap_n: str = "",
    cap_c: str = "",
    protein_leaprc: str = "leaprc.protein.ff14SB",
    water_leaprc: str = "leaprc.water.tip3p",
    extra_bonds: Optional[List[Tuple[str, str]]] = None,
) -> str:
    """Render a self-contained tleap script that emits a PDB."""
    res_block = sequence_to_tleap_residues(
        sequence, cap_n=cap_n, cap_c=cap_c
    )
    lines = [
        "# Auto-generated by abmptools.formulation.peptide_atomistic",
        f"source {protein_leaprc}",
        f"source {water_leaprc}",
        f"pep = sequence {res_block}",
    ]
    for a, b in extra_bonds or []:
        lines.append(f"bond pep.{a} pep.{b}")
    lines.extend([
        f"savepdb pep {out_pdb}",
        "quit",
        "",
    ])
    return "\n".join(lines)


def build_peptide_from_sequence(
    *,
    sequence: str,
    out_pdb: str,
    workdir: str,
    tleap_path: str = "tleap",
    cap_n: str = "",
    cap_c: str = "",
    protein_leaprc: str = "leaprc.protein.ff14SB",
    water_leaprc: str = "leaprc.water.tip3p",
    extra_bonds: Optional[List[Tuple[str, str]]] = None,
) -> str:
    """tleap-build a single peptide and return the PDB path."""
    wd = ensure_dir(workdir)
    tleap_in_path = str(wd / "build_peptide.tleap")
    abs_pdb = str(Path(out_pdb).resolve())
    text = render_tleap_input_from_sequence(
        sequence=sequence,
        out_pdb=abs_pdb,
        cap_n=cap_n,
        cap_c=cap_c,
        protein_leaprc=protein_leaprc,
        water_leaprc=water_leaprc,
        extra_bonds=extra_bonds,
    )
    write_text(tleap_in_path, text)
    result = run_command(
        [tleap_path, "-f", tleap_in_path], cwd=str(wd), check=False,
    )
    log_path = wd / "build_peptide.log"
    log_path.write_text(
        (result.stdout or "") + "\n\n--- stderr ---\n" + (result.stderr or "")
    )
    if result.returncode != 0:
        raise CommandError(
            cmd=f"{tleap_path} -f {tleap_in_path}",
            returncode=result.returncode,
            stderr=(result.stderr or "")[:500],
        )
    if not Path(abs_pdb).is_file():
        raise RuntimeError(
            f"tleap completed but did not produce {abs_pdb}. "
            f"Check {log_path} for details."
        )
    return abs_pdb


_HET_LINE = re.compile(r"^(ATOM  |HETATM)")


def normalize_existing_pdb(
    *,
    src_pdb: str,
    out_pdb: str,
    strip_waters: bool = True,
    strip_hetatm: bool = False,
    force_resname: str = "",
    force_resnum: int = 0,
) -> str:
    """Strip CRYST1/CONECT (and optionally waters) from a PDB.

    Used when the user provides a pre-built PDB (e.g. RCSB 2G4M).
    Keeps the existing residue numbering / chain ids intact, only
    filters out non-ATOM/HETATM lines and (optionally) HOH / WAT.

    Parameters
    ----------
    force_resname
        If non-empty, rewrites every ATOM/HETATM resname (cols 18-20)
        to this 3-letter tag. Needed for GAFF whole-peptide mode where
        acpype enforces "only one residue".
    force_resnum
        If non-zero, rewrites every ATOM/HETATM residue number
        (cols 23-26) to this integer.
    """
    src = Path(src_pdb).resolve()
    dst = Path(out_pdb).resolve()
    dst.parent.mkdir(parents=True, exist_ok=True)
    rname_3 = force_resname.strip().ljust(3)[:3] if force_resname else ""
    out_lines: List[str] = []
    for line in src.read_text().splitlines():
        if line.startswith(("CRYST1", "CONECT", "END", "MASTER", "ANISOU")):
            continue
        if not _HET_LINE.match(line):
            if line.startswith("TER"):
                # Drop TER between residues when forcing a single resname
                if not rname_3:
                    out_lines.append(line)
            continue
        resname = line[17:20].strip()
        if strip_waters and resname in ("HOH", "WAT", "SOL", "TIP3"):
            continue
        if strip_hetatm and line.startswith("HETATM"):
            continue
        # Rewrite cols 18-20 (resname) and / or 23-26 (resnum).
        if rname_3 or force_resnum:
            padded = (line + " " * 80)[:80]
            line_chars = list(padded)
            if rname_3:
                line_chars[17:20] = list(rname_3)
            if force_resnum:
                line_chars[22:26] = list(f"{force_resnum:>4d}")
            line = "".join(line_chars).rstrip()
        out_lines.append(line)
    out_lines.append("END")
    dst.write_text("\n".join(out_lines) + "\n")
    return str(dst)


__all__ = [
    "build_peptide_from_sequence",
    "normalize_existing_pdb",
    "render_tleap_input_from_sequence",
    "sequence_to_tleap_residues",
]
