# -*- coding: utf-8 -*-
"""tleap-based unified topology compose for the formulation builder.

Takes a packmol-mixed PDB (peptide × N_copies + enhancer × M_charged
+ M_neutral + bile salt × K, all heavy atoms only) and ligand
parameter files from acpype, then runs a single tleap session that:

1. ``source leaprc.protein.ff14SB``
2. ``source leaprc.water.tip3p`` (provides TIP3P + JC ions)
3. ``loadAmberParams frcmod.ionsjc_tip3p`` (explicit, harmless)
4. ``loadmol2`` + ``loadAmberParams`` per ligand species
5. ``sys = loadpdb mixture.pdb``
6. ``solvatebox sys TIP3PBOX <margin>``
7. ``addions sys Na+ 0``  +  ``addions sys Cl- N``  (Joung-Cheatham)
8. ``saveAmberParm sys system.prmtop system.inpcrd``
9. ``parmed`` → ``system.top`` + ``system.gro``

The same tleap recipe is used both at build time (via the orchestrator)
and inside ``test_formulation_topology.py`` (with the subprocess
mocked).
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence

from .models import FormulationBuildConfig
from .small_molecule import SmallMoleculeResult
from ._subprocess import CommandError, ensure_dir, run_command, write_text

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# tleap input rendering
# ---------------------------------------------------------------------------


def render_unified_tleap_input(
    *,
    config: FormulationBuildConfig,
    mixture_pdb: str,
    small_molecules: Sequence[SmallMoleculeResult],
    solvatebox_margin_nm: float,
    target_nacl_molarity: float,
    prmtop_out: str,
    inpcrd_out: str,
    extra_bonds: Optional[List[str]] = None,
) -> str:
    """Render a self-contained tleap script.

    *solvatebox_margin_nm* sets the outer solvent shell thickness;
    tleap's TIP3PBOX argument is in Angstrom.
    """
    margin_A = solvatebox_margin_nm * 10.0
    gaff_leaprc = f"leaprc.{config.gaff_version}"  # gaff2 → leaprc.gaff2
    lines: List[str] = [
        "# Auto-generated by abmptools.formulation.topology",
        f"source {config.amber_protein_ff}",
        f"source {config.amber_water_ff}",
        f"source {gaff_leaprc}",
        "loadAmberParams frcmod.ionsjc_tip3p",
    ]
    # Load each ligand species (uses mol2 atom types + frcmod params)
    for sm in small_molecules:
        lines.append(
            f"loadAmberParams {sm.frcmod}"
        )
        lines.append(
            f"{sm.resname} = loadmol2 {sm.mol2}"
        )
    # Load the packmol mixture (peptide multi-copy + small molecules)
    lines.append(f"sys = loadpdb {mixture_pdb}")
    if extra_bonds:
        lines.extend(extra_bonds)
    # Solvate
    lines.append(f"solvatebox sys TIP3PBOX {margin_A:.2f}")
    # Neutralise + add salt
    if config.system.neutralize:
        lines.append("addions sys Na+ 0")
        lines.append("addions sys Cl- 0")
    if target_nacl_molarity > 0:
        # Approximate count from box volume * concentration
        # tleap accepts an integer; the orchestrator computes this and
        # injects via *extra_addions_count*. Default = 0 means rely on
        # neutralise only.
        pass
    # Save AMBER files
    lines.append("charge sys")
    lines.append(f"saveAmberParm sys {prmtop_out} {inpcrd_out}")
    lines.append("quit")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# tleap runner
# ---------------------------------------------------------------------------


def run_tleap(
    *,
    tleap_input: str,
    workdir: str,
    tleap_path: str = "tleap",
) -> str:
    """Run tleap; return path to the leap log."""
    wd = ensure_dir(workdir)
    log_path = wd / "system_tleap.log"
    result = run_command(
        [tleap_path, "-f", tleap_input], cwd=str(wd), check=False,
    )
    log_path.write_text(
        f"=== argv ===\n{tleap_path} -f {tleap_input}\n\n"
        f"=== stdout ===\n{result.stdout or ''}\n"
        f"=== stderr ===\n{result.stderr or ''}\n"
        f"=== returncode ===\n{result.returncode}\n"
    )
    if result.returncode != 0:
        raise CommandError(
            cmd=f"{tleap_path} -f {tleap_input}",
            returncode=result.returncode,
            stderr=(result.stderr or "")[:500],
        )
    return str(log_path)


# ---------------------------------------------------------------------------
# AMBER → GROMACS via parmed
# ---------------------------------------------------------------------------


def amber_to_gromacs(
    *,
    prmtop: str,
    inpcrd: str,
    top_out: str,
    gro_out: str,
) -> None:
    """Convert prmtop + inpcrd to GROMACS top + gro via parmed (lazy import)."""
    try:
        import parmed as pmd  # type: ignore
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "parmed is required to emit GROMACS topology. "
            "Install via `pip install abmptools[formulation]` or "
            "`pip install parmed>=4.0`."
        ) from exc

    parm = pmd.load_file(prmtop, xyz=inpcrd)
    parm.save(top_out, format="gromacs", overwrite=True)
    parm.save(gro_out, overwrite=True)


# ---------------------------------------------------------------------------
# High-level entry point
# ---------------------------------------------------------------------------


@dataclass
class TopologyArtifacts:
    prmtop: str
    inpcrd: str
    top: str
    gro: str
    tleap_input: str
    tleap_log: str


def _patch_mixture_pdb_with_ter_records(mixture_pdb: Path) -> Path:
    """packmol output に **chain 境界の TER record を挿入**する patch。

    packmol は input PDB の TER record を **drop** するため、 multi-chain
    protein (例: insulin A 鎖 + B 鎖) を loadpdb で読むと tleap が
    chain 境界を認識できず、 20+ Å の異常 peptide bond を作ろうとして
    OXT atom が未定義になり fatal error。

    本関数は ATOM/HETATM 行を順次走査し、 ``chain ID`` が変わる位置
    (前 chain が空白でない場合) に ``TER`` 行を挿入する。 small molecule
    (chain ID = 空白) と protein (chain ID = A/B/...) の境界には挿入しない
    (packmol/tleap 慣習で small mol は 1 residue = 1 chain として扱われる)。

    Returns
    -------
    Path
        patch 後の PDB (in-place で上書き)。
    """
    pdb_path = Path(mixture_pdb)
    lines = pdb_path.read_text().splitlines(keepends=False)
    out: List[str] = []
    prev_chain = ""
    prev_resname = ""
    prev_resnum_str = ""
    prev_resnum_int = -1
    prev_atom_serial = 0
    ter_inserted = 0
    for line in lines:
        if line.startswith(("ATOM", "HETATM")) and len(line) >= 27:
            atom_serial_str = line[6:11].strip()
            atom_serial = int(atom_serial_str) if atom_serial_str.isdigit() else 0
            chain = line[21]
            resname = line[17:20].strip()
            resnum_str = line[22:26]
            try:
                resnum_int = int(resnum_str.strip())
            except ValueError:
                resnum_int = -1
            # TER 挿入条件:
            #   1) chain ID が変わった (前 chain が non-empty)
            #   2) resnum が大幅に減少 (multi-chain protein 内で
            #      A 鎖 21 → B 鎖 1 の遷移、 packmol が chain ID
            #      を統一してしまうケースに対応)
            chain_transition = (
                prev_chain != ""
                and chain != prev_chain
                and prev_chain != " "
            )
            resnum_reset = (
                prev_resnum_int > 0
                and resnum_int > 0
                and resnum_int < prev_resnum_int
                and (prev_resnum_int - resnum_int) >= 3
            )
            if chain_transition or resnum_reset:
                ter_chain = prev_chain if prev_chain.strip() else " "
                ter_line = (
                    f"TER   {prev_atom_serial + 1:>5}      "
                    f"{prev_resname:>3} {ter_chain}{prev_resnum_str}"
                )
                out.append(ter_line)
                ter_inserted += 1
            prev_chain = chain
            prev_resname = resname
            prev_resnum_str = resnum_str
            prev_resnum_int = resnum_int
            prev_atom_serial = atom_serial
        out.append(line)
    if ter_inserted > 0:
        logger.info(
            "Inserted %d TER records at chain boundaries in %s "
            "(multi-chain protein support).",
            ter_inserted, pdb_path,
        )
        pdb_path.write_text("\n".join(out) + "\n")
    return pdb_path


def build_topology(
    *,
    config: FormulationBuildConfig,
    mixture_pdb: str,
    small_molecules: Sequence[SmallMoleculeResult],
    workdir: str,
    solvatebox_margin_nm: Optional[float] = None,
    extra_bonds: Optional[List[str]] = None,
) -> TopologyArtifacts:
    """Run the unified tleap recipe and emit GROMACS files.

    Returns
    -------
    TopologyArtifacts
        Paths to all intermediate + final files.
    """
    wd = ensure_dir(workdir)
    prmtop = str(wd / "system.prmtop")
    inpcrd = str(wd / "system.inpcrd")
    top_path = str(wd / "system.top")
    gro_path = str(wd / "system.gro")

    # multi-chain protein 用の patch: packmol output に TER record を挿入
    _patch_mixture_pdb_with_ter_records(Path(mixture_pdb))

    margin = (
        solvatebox_margin_nm
        if solvatebox_margin_nm is not None
        else config.packmol_inner_box_margin_nm
    )
    tleap_in_path = str(wd / "system.tleap")
    tleap_text = render_unified_tleap_input(
        config=config,
        mixture_pdb=str(Path(mixture_pdb).resolve()),
        small_molecules=small_molecules,
        solvatebox_margin_nm=margin,
        target_nacl_molarity=config.system.salt_concentration_M,
        prmtop_out=prmtop,
        inpcrd_out=inpcrd,
        extra_bonds=extra_bonds,
    )
    write_text(tleap_in_path, tleap_text)

    log_path = run_tleap(
        tleap_input=tleap_in_path, workdir=str(wd),
        tleap_path=config.tleap_path,
    )
    if not Path(prmtop).is_file() or not Path(inpcrd).is_file():
        raise RuntimeError(
            f"tleap completed but {prmtop} / {inpcrd} are missing. "
            f"Check {log_path}."
        )
    amber_to_gromacs(
        prmtop=prmtop, inpcrd=inpcrd, top_out=top_path, gro_out=gro_path,
    )
    return TopologyArtifacts(
        prmtop=prmtop,
        inpcrd=inpcrd,
        top=top_path,
        gro=gro_path,
        tleap_input=tleap_in_path,
        tleap_log=log_path,
    )


__all__ = [
    "TopologyArtifacts",
    "amber_to_gromacs",
    "build_topology",
    "render_unified_tleap_input",
    "run_tleap",
]
