# -*- coding: utf-8 -*-
"""Umbrella sampling: peptide release from an aggregate.

Refactors :mod:`abmptools.membrane.pulling` + :mod:`abmptools.membrane.umbrella`
to use pull groups (Aggregate, Target_Peptide) instead of
(Bilayer, Peptide). For now the module *generates* the run.sh, mdps,
and index entries; actual mdrun + wham execution is delegated to the
user (or to the slow integration tests).
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from ._subprocess import ensure_dir, write_text
from .models import FormulationBuildConfig, USProtocol

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pull MDP
# ---------------------------------------------------------------------------


PULL_MDP_TEMPLATE = """; Auto-generated by abmptools.formulation.umbrella_release
integrator               = md
dt                       = 0.002
nsteps                   = {pull_nsteps}

nstxout-compressed       = 500
nstenergy                = 1000
nstlog                   = 1000

cutoff-scheme            = Verlet
nstlist                  = 20
coulombtype              = PME
rcoulomb                 = 1.2
vdwtype                  = Cut-off
vdw-modifier             = Force-switch
rvdw-switch              = 1.0
rvdw                     = 1.2

tcoupl                   = V-rescale
tc-grps                  = Peptide_Solute Non_Peptide
tau_t                    = 1.0 1.0
ref_t                    = 310 310

pcoupl                   = no

constraints              = h-bonds
constraint-algorithm     = LINCS

pull                     = yes
pull-ngroups             = 2
pull-ncoords             = 1
pull-group1-name         = Non_Peptide
pull-group2-name         = Peptide
pull-pbc-ref-prev-step-com = yes
pull-coord1-type         = umbrella
pull-coord1-geometry     = direction-periodic
pull-coord1-dim          = N N Y
pull-coord1-vec          = 0 0 1
pull-coord1-groups       = 1 2
pull-coord1-rate         = {pull_rate}
pull-coord1-k            = {pull_k}
pull-coord1-start        = yes
pull-nstxout             = 500
pull-nstfout             = 500
"""


WINDOW_MDP_TEMPLATE = """; Auto-generated by abmptools.formulation.umbrella_release
integrator               = md
dt                       = {dt}
nsteps                   = {nsteps}

nstxout-compressed       = 1000
nstenergy                = 500
nstlog                   = 500

cutoff-scheme            = Verlet
nstlist                  = 20
coulombtype              = PME
rcoulomb                 = 1.2
vdwtype                  = Cut-off
vdw-modifier             = Force-switch
rvdw-switch              = 1.0
rvdw                     = 1.2

tcoupl                   = V-rescale
tc-grps                  = Peptide_Solute Non_Peptide
tau_t                    = 1.0 1.0
ref_t                    = 310 310

pcoupl                   = c-rescale
pcoupltype               = isotropic
tau_p                    = 5.0
ref_p                    = 1.0
compressibility          = 4.5e-5

constraints              = h-bonds
constraint-algorithm     = LINCS

pull                     = yes
pull-ngroups             = 2
pull-ncoords             = 1
pull-group1-name         = Non_Peptide
pull-group2-name         = Peptide
pull-pbc-ref-prev-step-com = yes
pull-coord1-type         = umbrella
pull-coord1-geometry     = direction
pull-coord1-dim          = N N Y
pull-coord1-vec          = 0 0 1
pull-coord1-groups       = 1 2
pull-coord1-rate         = 0.0
pull-coord1-k            = {k}
pull-coord1-init         = {target_dist}
pull-coord1-start        = no
pull-nstxout             = 1000
pull-nstfout             = 1000
"""


def render_pull_mdp(us: USProtocol) -> str:
    return PULL_MDP_TEMPLATE.format(
        pull_nsteps=us.pull_nsteps,
        pull_rate=us.pull_rate_nm_per_ps,
        pull_k=us.force_constant_kj_mol_nm2,
    )


def render_window_mdp(us: USProtocol, *, target_dist_nm: float) -> str:
    return WINDOW_MDP_TEMPLATE.format(
        dt=us.window_dt_ps,
        nsteps=us.window_nsteps,
        k=us.force_constant_kj_mol_nm2,
        target_dist=target_dist_nm,
    )


# ---------------------------------------------------------------------------
# Layout writer
# ---------------------------------------------------------------------------


@dataclass
class USArtifacts:
    pull_mdp: str
    window_mdps: List[str]
    window_targets_nm: List[float]
    n_windows: int
    out_dir: str
    run_script: str = ""


_RUN_US_SH_TEMPLATE = r"""#!/usr/bin/env bash
# Auto-generated by abmptools.formulation.umbrella_release.
# Expects build artifacts at ../{system.top, system.gro, system.ndx}.
set -euo pipefail
cd "$(dirname "$0")"

GMX="${GMX:-__GMX__}"
NT="${NT:-4}"
export OMP_NUM_THREADS="$NT"
MDRUN_OPTS="${MDRUN_OPTS:-}"
MAXWARN="${GROMPP_MAXWARN:-5}"
TEMP="${TEMP:-__TEMP__}"

TOP="../system.top"
# Prefer the post-NPT structure (../prod/prod.gro or ../equil/npt.gro)
# so the pull stage starts from a properly equilibrated box; the raw
# tleap-output ``system.gro`` often has water in unfavourable
# positions that cause SETTLE failures.
if [ -f "../prod/prod.gro" ]; then
    GRO0="../prod/prod.gro"
elif [ -f "../equil/npt.gro" ]; then
    GRO0="../equil/npt.gro"
else
    GRO0="../system.gro"
fi
NDX="../system.ndx"

# --- 1. pull (steered MD: Non_Peptide vs Peptide) ---
"$GMX" grompp -f pull.mdp -p "$TOP" -c "$GRO0" -n "$NDX" \
    -o pull.tpr -po pull.mdp_out -maxwarn "$MAXWARN"
"$GMX" mdrun -deffnm pull -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

# --- 2. extract window initial frames from pull trajectory ---
GMX="$GMX" python3 - <<'PYEOF'
import os, subprocess
import numpy as np

targets = __TARGETS__
pullx_path = "pull_pullx.xvg" if os.path.exists("pull_pullx.xvg") else "pullx.xvg"
pullx = np.loadtxt(pullx_path, comments=["#", "@"])
times = pullx[:, 0]
distances = pullx[:, 1]
gmx = os.environ["GMX"]

for i, t in enumerate(targets):
    j = int(np.argmin(np.abs(distances - t)))
    frame_time_ps = float(times[j])
    out_gro = f"window_{i:02d}_start.gro"
    subprocess.run(
        f'echo 0 | {gmx} trjconv -f pull.xtc -s pull.tpr -dump {frame_time_ps:.1f} -o {out_gro}',
        shell=True, check=True,
    )
    print(f"window {i:02d}: target={t:.2f} nm at t={frame_time_ps:.1f} ps -> {out_gro}")
PYEOF

# --- 3. window mdrun (each window: NPT umbrella) ---
for i in $(seq -f "%02g" 0 __N_MINUS_1__); do
    "$GMX" grompp -f window_${i}.mdp -p "$TOP" -c window_${i}_start.gro -n "$NDX" \
        -o window_${i}.tpr -po window_${i}.mdp_out -maxwarn "$MAXWARN"
    "$GMX" mdrun -deffnm window_${i} -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS \
        -px window_${i}_pullx.xvg -pf window_${i}_pullf.xvg
done

# --- 4. WHAM ---
ls window_*.tpr > tpr.dat
ls window_*_pullx.xvg > pullx.dat
"$GMX" wham -it tpr.dat -ix pullx.dat -o pmf.xvg -hist histo.xvg -temp "$TEMP" -unit kJ

echo "=== release_us complete ==="
echo "PMF: $(pwd)/pmf.xvg"
echo "histograms: $(pwd)/histo.xvg"
"""


def render_run_us_script(
    *,
    gmx_path: str,
    n_windows: int,
    targets_nm: List[float],
    temperature_K: float,
) -> str:
    txt = _RUN_US_SH_TEMPLATE
    txt = txt.replace("__GMX__", gmx_path)
    txt = txt.replace("__N_MINUS_1__", str(n_windows - 1))
    txt = txt.replace("__TARGETS__", repr(targets_nm))
    txt = txt.replace("__TEMP__", str(temperature_K))
    return txt


def _find_median_atom_in_ndx_group(ndx_path: str, group_name: str) -> int:
    """Return the median atom index (1-based) of a named group in the ndx.

    Used to set ``pull-groupN-pbcatom`` when the group spans the box (e.g.
    solvent or ``Non_Peptide``).
    """
    from pathlib import Path
    lines = Path(ndx_path).read_text().splitlines()
    in_group = False
    ids: List[int] = []
    target = f"[ {group_name} ]"
    for ln in lines:
        if ln.strip().startswith("["):
            in_group = ln.strip() == target
            continue
        if in_group and ln.strip():
            for tok in ln.split():
                try:
                    ids.append(int(tok))
                except ValueError:
                    pass
    if not ids:
        raise RuntimeError(
            f"_find_median_atom_in_ndx_group: group {group_name!r} not found "
            f"or empty in {ndx_path}"
        )
    ids.sort()
    return ids[len(ids) // 2]


def write_release_us_layout(
    *,
    config: FormulationBuildConfig,
    out_dir: str,
    initial_distance_nm: float = 0.0,
    pbcatom_group1: int = 0,
    pbcatom_group2: int = 0,
) -> USArtifacts:
    """Write the pull MDP + N window MDPs into ``<out_dir>/us/``.

    *initial_distance_nm* is the COM-COM separation between
    Aggregate and Target_Peptide at the start of pulling (typically
    ~0 nm if the target is buried in the aggregate). Window targets
    are spaced from this distance outward by ``window_spacing_nm``.
    """
    if config.release_us is None:
        raise ValueError(
            "FormulationBuildConfig.release_us is None — populate it "
            "before calling write_release_us_layout."
        )
    us = config.release_us
    od = ensure_dir(Path(out_dir) / "us")

    # Auto-detect pbcatom for groups that may span the box.
    parent = Path(out_dir)
    ndx_path = parent / "system.ndx"
    if pbcatom_group1 == 0 and ndx_path.is_file():
        try:
            pbcatom_group1 = _find_median_atom_in_ndx_group(
                str(ndx_path), "Non_Peptide"
            )
        except RuntimeError:
            pbcatom_group1 = 0

    pull_mdp = od / "pull.mdp"
    pull_text = render_pull_mdp(us)
    if pbcatom_group1:
        pull_text = pull_text.replace(
            "pull-group1-name         = Non_Peptide",
            (
                "pull-group1-name         = Non_Peptide\n"
                f"pull-group1-pbcatom      = {pbcatom_group1}"
            ),
        )
    write_text(pull_mdp, pull_text)

    window_mdps: List[str] = []
    targets: List[float] = []
    for i in range(us.n_windows):
        dist = initial_distance_nm + i * us.window_spacing_nm
        targets.append(dist)
        mdp = od / f"window_{i:02d}.mdp"
        win_text = render_window_mdp(us, target_dist_nm=dist)
        if pbcatom_group1:
            win_text = win_text.replace(
                "pull-group1-name         = Non_Peptide",
                (
                    "pull-group1-name         = Non_Peptide\n"
                    f"pull-group1-pbcatom      = {pbcatom_group1}"
                ),
            )
        write_text(mdp, win_text)
        window_mdps.append(str(mdp))

    run_path = od / "run_us.sh"
    write_text(
        run_path,
        render_run_us_script(
            gmx_path=config.gmx_path,
            n_windows=us.n_windows,
            targets_nm=targets,
            temperature_K=config.production.temperature_K,
        ),
    )
    run_path.chmod(0o755)

    return USArtifacts(
        pull_mdp=str(pull_mdp),
        window_mdps=window_mdps,
        window_targets_nm=targets,
        n_windows=us.n_windows,
        out_dir=str(od),
        run_script=str(run_path),
    )


def run_release_us(
    *,
    config: FormulationBuildConfig,
    target_peptide_idx: int = 0,
) -> USArtifacts:
    """Entry point invoked by the CLI ``release_us`` subcommand.

    For now this only writes the layout; actual mdrun + wham execution
    is left to the user (or the slow integration tests).
    """
    if config.release_us is None:
        config.release_us = USProtocol(target_peptide_idx=target_peptide_idx)
    else:
        config.release_us.target_peptide_idx = target_peptide_idx
    return write_release_us_layout(
        config=config, out_dir=config.output_dir,
    )


__all__ = [
    "USArtifacts",
    "render_pull_mdp",
    "render_window_mdp",
    "run_release_us",
    "write_release_us_layout",
]
