# -*- coding: utf-8 -*-
"""
abmptools.membrane.umbrella
---------------------------
Per-window MDP and run-script generation for umbrella sampling.

For each window i ∈ [0, n_windows), write
``windows/win_{i:03d}/window.mdp`` containing a static pull-coord
(``pull-coord1-rate = 0``) at ``z_min + i * dz``. The actual MD
invocation (``gmx grompp`` + ``gmx mdrun``) is encoded in ``run.sh``
written by :func:`write_run_script`.
"""
from __future__ import annotations

import logging
import os
import stat
from pathlib import Path
from typing import Dict, Optional

from .models import MembraneConfig
from .mdp_us_protocol import render_npt_mdp, render_pull_block
from .pulling import _override_mdp_field

logger = logging.getLogger(__name__)


def write_window_mdps(
    *, config: MembraneConfig, windows_dir: str,
    pbc_atom_g1: Optional[int] = None,
) -> Dict[int, str]:
    """Write per-window MDPs (one per umbrella window).

    Each window MDP is the NPT-semiisotropic template + a pull block
    with ``rate=0`` and ``init = z_min + i * dz``.

    Parameters
    ----------
    pbc_atom_g1 : int or None
        Bilayer group's PBC reference atom (1-based). Required when
        the Bilayer diameter exceeds half the shortest box vector;
        compute with :func:`pulling.find_pbc_center_atom`.

    Returns
    -------
    dict
        Mapping window index → absolute path to that window's MDP.
    """
    wd = Path(windows_dir).resolve()
    wd.mkdir(parents=True, exist_ok=True)

    u = config.umbrella
    out: Dict[int, str] = {}

    npt_body = render_npt_mdp(config=config, pcoupl="c-rescale")
    npt_body = _override_mdp_field(npt_body, "nsteps", str(u.window_nsteps))
    npt_body = _override_mdp_field(npt_body, "dt", f"{u.window_dt_ps:.3f}")
    npt_body = _override_mdp_field(
        npt_body, "nstxout-compressed", str(u.window_nstxtcout),
    )
    npt_body = _override_mdp_field(
        npt_body, "nstenergy", str(u.window_nstenergy),
    )

    for i in range(u.n_windows):
        z_target = u.z_min_nm + i * u.window_spacing_nm
        win_dir = wd / f"win_{i:03d}"
        win_dir.mkdir(parents=True, exist_ok=True)

        pull_body = render_pull_block(
            config=config,
            pull_init_nm=z_target,
            pull_rate_nm_per_ps=0.0,
            pull_k=u.force_constant_kj_mol_nm2,
            nst_pull_xf=u.window_nstxtcout,
            pbc_atom_g1=pbc_atom_g1,
        )

        text = (
            f"; window {i:03d}.mdp — static umbrella at z = {z_target:+.3f} nm\n"
            "; (NPT-semiisotropic chassis + static pull-code block)\n"
            + npt_body.replace("; npt.mdp — semiisotropic NPT\n", "", 1)
            + "\n"
            + pull_body
        )
        mdp_path = win_dir / "window.mdp"
        mdp_path.write_text(text)
        out[i] = str(mdp_path)

    logger.info("wrote %d window MDPs in %s", len(out), wd)
    return out


def write_run_script(
    *,
    config: MembraneConfig,
    top: str, gro: str, ndx: str,
    equil_mdps: Dict[str, str],
    pull_mdp: str,
    window_mdps: Dict[int, str],
    output_dir: str,
) -> str:
    """Write the top-level POSIX bash run script.

    The script encodes (roughly):

      1. em → nvt → npt equilibration (sequential)
      2. pulling MD (uses npt.gro as input)
      3. python -m abmptools.membrane.pulling  → extract window frames
      4. per-window grompp + mdrun (sequential — replace with GNU
         parallel or job-array for HPC)
      5. python -m abmptools.membrane.pmf  → gmx wham + plots

    Returns the absolute path to ``run.sh``.
    """
    out_dir = Path(output_dir).resolve()
    script_path = out_dir / "run.sh"

    # Use relative paths within the output directory for portability.
    def rel(p: str) -> str:
        return os.path.relpath(p, str(out_dir))

    em_mdp = rel(equil_mdps["em"])
    nvt_mdp = rel(equil_mdps["nvt"])
    npt_mdp = rel(equil_mdps["npt"])
    pull_mdp_rel = rel(pull_mdp)
    top_rel = rel(top)
    gro_rel = rel(gro)
    ndx_rel = rel(ndx)

    n_windows = len(window_mdps)

    content = f"""#!/usr/bin/env bash
# Auto-generated by abmptools.membrane.umbrella.write_run_script.
# Edit GMX/NT/MPI variables to match your cluster, then run from {out_dir}.
set -euo pipefail
cd "$(dirname "$0")"

# --- tool paths (override via env if needed) ---
GMX="${{GMX:-{config.gmx_path}}}"
NT="${{NT:-4}}"            # total threads (single-rank OpenMP)
# Constrain OpenMP to NT to avoid mismatches with auto-detected CPU.
export OMP_NUM_THREADS="$NT"

# --- mdrun extra options (e.g. GPU offload) ---
# Default empty (CPU only). To use GPU offload (NVIDIA via CUDA / OpenCL,
# or AMD via OpenCL):
#     MDRUN_OPTS="-nb gpu -pme gpu -pmefft gpu -bonded gpu -update gpu" bash run.sh
# Conservative GPU (PME on GPU, bonded on CPU; works with older drivers):
#     MDRUN_OPTS="-nb gpu -pme gpu" bash run.sh
MDRUN_OPTS="${{MDRUN_OPTS:-}}"

# --- file paths (relative to this script) ---
TOP="{top_rel}"
GRO0="{gro_rel}"           # initial structure (post-packmol-memgen + parmed)
NDX="{ndx_rel}"

# ---------- Stage 1: energy minimisation ----------
mkdir -p equil
"$GMX" grompp -f {em_mdp} -p "$TOP" -c "$GRO0" -n "$NDX" \\
    -o equil/em.tpr -po equil/em.mdp_out -maxwarn 1
# em is steepest-descent — keep on CPU; GPU offload doesn't speed up SD.
"$GMX" mdrun -deffnm equil/em -ntmpi 1 -ntomp "$NT"

# ---------- Stage 2: NVT ----------
"$GMX" grompp -f {nvt_mdp} -p "$TOP" -c equil/em.gro -n "$NDX" \\
    -o equil/nvt.tpr -po equil/nvt.mdp_out -maxwarn 1
"$GMX" mdrun -deffnm equil/nvt -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

# ---------- Stage 3: NPT-semiisotropic ----------
"$GMX" grompp -f {npt_mdp} -p "$TOP" -c equil/nvt.gro -n "$NDX" \\
    -o equil/npt.tpr -po equil/npt.mdp_out -maxwarn 1
"$GMX" mdrun -deffnm equil/npt -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

# ---------- Stage 4: pulling (steered MD along z) ----------
mkdir -p pull
"$GMX" grompp -f {pull_mdp_rel} -p "$TOP" -c equil/npt.gro -n "$NDX" \\
    -o pull/pull.tpr -po pull/pull.mdp_out -maxwarn 1
"$GMX" mdrun -deffnm pull/pull -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS \\
    -px pull/pullx.xvg -pf pull/pullf.xvg

# ---------- Stage 5: extract per-window starting frames ----------
# Pass --gmx-path so trjconv reads .tpr with the same gmx version that
# produced it (.tpr files are version-locked).
python -m abmptools.membrane.pulling \\
    --pull-tpr pull/pull.tpr --pull-xtc pull/pull.xtc \\
    --pull-xvg pull/pullx.xvg \\
    --config input/config.json \\
    --windows-dir windows \\
    --gmx-path "$GMX"

# ---------- Stage 6: per-window MD ----------
for i in $(seq -f '%03g' 0 {n_windows - 1}); do
    WIN="windows/win_$i"
    "$GMX" grompp -f "$WIN/window.mdp" -p "$TOP" -c "$WIN/start.gro" \\
        -n "$NDX" -o "$WIN/window.tpr" -po "$WIN/window.mdp_out" \\
        -maxwarn 1
    "$GMX" mdrun -deffnm "$WIN/window" -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS \\
        -px "$WIN/pullx.xvg" -pf "$WIN/pullf.xvg"
done

# ---------- Stage 7: PMF analysis ----------
python -m abmptools.membrane.pmf \\
    --windows-dir windows \\
    --config input/config.json \\
    --analysis-dir analysis \\
    --gmx-path "$GMX"

echo "=== run.sh complete ==="
"""
    script_path.write_text(content)
    # chmod +x
    st = os.stat(script_path)
    os.chmod(script_path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return str(script_path)
