# -*- coding: utf-8 -*-
"""
abmptools.genesis.mmgbsa.system_builder
---------------------------------------
Generate AMBER ``prmtop`` + ``inpcrd`` for the three GENESIS MM/GBSA
systems (``complex`` / ``ligand`` / ``receptor``) via ``tleap``.

Mirrors POC ``2_setupmd.py``: each leaprc is rendered with the same
6 ``source`` lines + ``addPdbResMap``/``addPdbAtomMap`` blocks, plus
``loadAmberParams <frcmod>`` / ``loadmol2 <mol2>`` for the ligand and
``combine`` for the complex.

License posture: AmberTools ``tleap`` is free for academic and
commercial use; subprocess-only invocation, no source modification.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import List

from ._subprocess import CommandError, run_command, write_text
from .models import ForceFieldSet

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Result containers
# ---------------------------------------------------------------------------

@dataclass
class TleapSystemResult:
    """Per-system tleap output paths.

    Each system writes its own ``leaprc`` file (for reproducibility) and
    runs tleap once to produce ``<name>.prmtop`` + ``<name>.inpcrd``.
    """
    leaprc: Path
    prmtop: Path
    inpcrd: Path
    pdb: Path           # savepdb output
    log: Path


@dataclass
class SystemBuildResult:
    """Combined tleap outputs for the three MM/GBSA systems."""
    complex: TleapSystemResult
    ligand: TleapSystemResult
    receptor: TleapSystemResult


# ---------------------------------------------------------------------------
# leaprc text rendering
# ---------------------------------------------------------------------------

def _render_ff_header(ff: ForceFieldSet) -> List[str]:
    """6 ``source`` lines + ``addPdbResMap``/``addPdbAtomMap`` blocks
    (POC convention)."""
    res_map = " ".join(f'{{ "{a}" "{b}" }}' for a, b in ff.add_pdb_res_map)
    atom_map = " ".join(f'{{ "{a}" "{b}" }}' for a, b in ff.add_pdb_atom_map)
    lines: List[str] = [
        "# Auto-generated by abmptools.genesis.mmgbsa.system_builder",
        "verbosity 2",
        f"source {ff.leaprc_protein}",
        f"source {ff.leaprc_dna}",
        f"source {ff.leaprc_rna}",
        f"source {ff.leaprc_water}",
        f"source {ff.leaprc_gaff2}",
        f"source {ff.leaprc_gaff}",
        f"addPdbResMap {{ {res_map} }}",
        f"addPdbAtomMap {{ {atom_map} }}",
    ]
    for extra in ff.extra_lines:
        lines.append(extra)
    return lines


def render_complex_leaprc(
    ff: ForceFieldSet,
    receptor_pdb: Path,
    frcmod: Path,
    mol2: Path,
    prmtop: Path,
    inpcrd: Path,
    out_pdb: Path,
) -> str:
    """Render leaprc for the ``complex`` system (protein + ligand)."""
    lines = _render_ff_header(ff) + [
        "# read ligand parameters",
        f"loadAmberParams {frcmod}",
        f"ligand = loadmol2 {mol2}",
        "# read protein structure",
        f"protein = loadpdb {receptor_pdb}",
        "# combine",
        "complex = combine { protein ligand }",
        f"savePdb complex {out_pdb}",
        f"saveAmberParm complex {prmtop} {inpcrd}",
        "quit",
        "",
    ]
    return "\n".join(lines)


def render_ligand_leaprc(
    ff: ForceFieldSet,
    frcmod: Path,
    mol2: Path,
    prmtop: Path,
    inpcrd: Path,
    out_pdb: Path,
) -> str:
    """Render leaprc for the ``ligand`` system (ligand only)."""
    lines = _render_ff_header(ff) + [
        "# read ligand parameters",
        f"loadAmberParams {frcmod}",
        f"ligand = loadmol2 {mol2}",
        f"savePdb ligand {out_pdb}",
        f"saveAmberParm ligand {prmtop} {inpcrd}",
        "quit",
        "",
    ]
    return "\n".join(lines)


def render_receptor_leaprc(
    ff: ForceFieldSet,
    receptor_pdb: Path,
    prmtop: Path,
    inpcrd: Path,
    out_pdb: Path,
) -> str:
    """Render leaprc for the ``receptor`` system (protein only)."""
    lines = _render_ff_header(ff) + [
        f"protein = loadpdb {receptor_pdb}",
        f"savePdb protein {out_pdb}",
        f"saveAmberParm protein {prmtop} {inpcrd}",
        "quit",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# tleap runner
# ---------------------------------------------------------------------------

def _run_one_tleap(
    leaprc: Path,
    workdir: Path,
    log: Path,
    tleap_path: str,
) -> None:
    """Invoke tleap on a single leaprc; persist combined log."""
    cmd = [tleap_path, "-f", str(leaprc)]
    logger.info("Running tleap: %s", " ".join(cmd))
    result = run_command(cmd, cwd=workdir, capture=True)
    log.write_text(
        f"=== argv ===\n{' '.join(cmd)}\n\n"
        f"=== stdout ===\n{result.stdout or ''}\n"
        f"=== stderr ===\n{result.stderr or ''}\n"
        f"=== returncode ===\n{result.returncode}\n"
    )


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------

def build_three_systems(
    receptor_pdb: Path,
    frcmod: Path,
    mol2: Path,
    workdir: Path,
    ff: ForceFieldSet,
    tleap_path: str = "tleap",
) -> SystemBuildResult:
    """Render 3 leaprc files + run tleap 3 times to produce
    ``complex`` / ``ligand`` / ``receptor`` AMBER parameter+coordinate
    files in *workdir*.

    Output filenames (POC convention):

    - ``complex.{prmtop, inpcrd, pdb}`` + ``leap_complex.log``
    - ``ligand.{prmtop, inpcrd, pdb}`` + ``leap_ligand.log``
    - ``receptor.{prmtop, inpcrd, pdb}`` + ``leap_receptor.log``
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    # 1. Complex
    complex_leaprc = workdir / "leaprc_complex"
    complex_pdb = workdir / "complex.pdb"
    complex_prmtop = workdir / "complex.prmtop"
    complex_inpcrd = workdir / "complex.inpcrd"
    complex_log = workdir / "leap_complex.log"
    write_text(
        complex_leaprc,
        render_complex_leaprc(
            ff=ff, receptor_pdb=receptor_pdb,
            frcmod=frcmod, mol2=mol2,
            prmtop=complex_prmtop, inpcrd=complex_inpcrd,
            out_pdb=complex_pdb,
        ),
    )
    _run_one_tleap(complex_leaprc, workdir, complex_log, tleap_path)
    if not complex_prmtop.exists():
        raise CommandError(
            cmd=f"{tleap_path} -f {complex_leaprc}",
            returncode=1,
            stderr=f"tleap (complex) finished but {complex_prmtop} missing.",
        )

    # 2. Ligand
    ligand_leaprc = workdir / "leaprc_ligand"
    ligand_pdb = workdir / "ligand.pdb"
    ligand_prmtop = workdir / "ligand.prmtop"
    ligand_inpcrd = workdir / "ligand.inpcrd"
    ligand_log = workdir / "leap_ligand.log"
    write_text(
        ligand_leaprc,
        render_ligand_leaprc(
            ff=ff, frcmod=frcmod, mol2=mol2,
            prmtop=ligand_prmtop, inpcrd=ligand_inpcrd,
            out_pdb=ligand_pdb,
        ),
    )
    _run_one_tleap(ligand_leaprc, workdir, ligand_log, tleap_path)
    if not ligand_prmtop.exists():
        raise CommandError(
            cmd=f"{tleap_path} -f {ligand_leaprc}",
            returncode=1,
            stderr=f"tleap (ligand) finished but {ligand_prmtop} missing.",
        )

    # 3. Receptor
    receptor_leaprc = workdir / "leaprc_receptor"
    receptor_out_pdb = workdir / "receptor.pdb"
    receptor_prmtop = workdir / "receptor.prmtop"
    receptor_inpcrd = workdir / "receptor.inpcrd"
    receptor_log = workdir / "leap_receptor.log"
    write_text(
        receptor_leaprc,
        render_receptor_leaprc(
            ff=ff, receptor_pdb=receptor_pdb,
            prmtop=receptor_prmtop, inpcrd=receptor_inpcrd,
            out_pdb=receptor_out_pdb,
        ),
    )
    _run_one_tleap(receptor_leaprc, workdir, receptor_log, tleap_path)
    if not receptor_prmtop.exists():
        raise CommandError(
            cmd=f"{tleap_path} -f {receptor_leaprc}",
            returncode=1,
            stderr=f"tleap (receptor) finished but {receptor_prmtop} missing.",
        )

    return SystemBuildResult(
        complex=TleapSystemResult(
            leaprc=complex_leaprc, prmtop=complex_prmtop,
            inpcrd=complex_inpcrd, pdb=complex_pdb, log=complex_log,
        ),
        ligand=TleapSystemResult(
            leaprc=ligand_leaprc, prmtop=ligand_prmtop,
            inpcrd=ligand_inpcrd, pdb=ligand_pdb, log=ligand_log,
        ),
        receptor=TleapSystemResult(
            leaprc=receptor_leaprc, prmtop=receptor_prmtop,
            inpcrd=receptor_inpcrd, pdb=receptor_out_pdb, log=receptor_log,
        ),
    )


__all__ = [
    "SystemBuildResult",
    "TleapSystemResult",
    "build_three_systems",
    "render_complex_leaprc",
    "render_ligand_leaprc",
    "render_receptor_leaprc",
]
