# -*- coding: utf-8 -*-
"""
abmptools.genesis.grest.grest_runner
------------------------------------
Emit ``run.sh`` orchestrator for the gREST_SSCR pipeline.

The script chains the four GENESIS / AmberTools stages produced by the
builder:

  step1: atdyn  -- minimisation (single rank)
  step2: spdyn  -- equilibration (small MPI, no replica)
  step3: spdyn  -- gREST_SSCR production (replica MPI)
  step5: remd_convert  -- parameter sort (post-MD)

Tool paths are configured via the standard environment variables
(``ATDYN``, ``SPDYN``, ``MPIRUN``, ``REMD_CONVERT``) so the script
works under conda/mamba environments without baked-in absolute paths.

HPC scheduler scaffolds (``run_pjsub.sh`` / ``run_sbatch.sh``) are
emitted as comment-only templates -- abmptools does not test them.
The user is expected to copy the relevant body and prepend their
site's submission directives.
"""
from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent

from ._subprocess import write_text
from .models import GrestBuildConfig

logger = logging.getLogger(__name__)


def write_run_script(
    cfg: GrestBuildConfig,
    n_replicas: int,
    out_path: Path,
) -> Path:
    """Render ``run.sh`` for the gREST pipeline.

    Parameters
    ----------
    cfg
        Validated :class:`GrestBuildConfig`.
    n_replicas
        Length of the temperature ladder (= ``[REMD] nreplica1``).
    out_path
        Destination path. The script is written with ``+x`` perms.
    """
    n_total = n_replicas * cfg.mpi_processes_per_replica
    script = dedent(f"""\
        #!/usr/bin/env bash
        # Auto-generated by abmptools.genesis.grest.grest_runner
        # GENESIS gREST_SSCR pipeline orchestrator.
        # Tool paths can be overridden via env vars (ATDYN, SPDYN,
        # REMD_CONVERT, MPIRUN). Defaults below match standard
        # GENESIS / OpenMPI installations.
        set -euo pipefail

        SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
        cd "$SCRIPT_DIR"

        ATDYN="${{ATDYN:-{cfg.atdyn_path}}}"
        SPDYN="${{SPDYN:-{cfg.spdyn_path}}}"
        MPIRUN="${{MPIRUN:-{cfg.mpirun_path}}}"
        REMD_CONVERT="${{REMD_CONVERT:-{cfg.remd_convert_path}}}"

        export OMP_NUM_THREADS={cfg.omp_num_threads}

        mkdir -p logs

        echo "[step1] atdyn minimisation"
        cd build
        "$ATDYN" ../inp/step1_minimize.inp 2>&1 | tee ../logs/step1.log
        cd "$SCRIPT_DIR"

        echo "[step2] spdyn equilibration ({cfg.mpi_processes_per_replica} MPI)"
        cd build
        "$MPIRUN" -np {cfg.mpi_processes_per_replica} \\
            "$SPDYN" ../inp/step2_equilibrate.inp 2>&1 | tee ../logs/step2.log
        cd "$SCRIPT_DIR"

        echo "[step3] spdyn gREST_SSCR ({n_replicas} replicas x {cfg.mpi_processes_per_replica} MPI = {n_total} procs)"
        cd build
        "$MPIRUN" -np {n_total} \\
            "$SPDYN" ../inp/step3_grest.inp 2>&1 | tee ../logs/step3.log
        cd "$SCRIPT_DIR"

        echo "[step5] remd_convert (parameter sort to lowest-T trajectory)"
        cd build
        "$REMD_CONVERT" ../inp/step5_remd_convert.inp 2>&1 | tee ../logs/step5.log
        cd "$SCRIPT_DIR"

        echo "Pipeline complete. Lowest-T trajectory: build/param1.dcd"
        """)
    write_text(out_path, script)
    out_path.chmod(0o755)
    return out_path


def write_pjsub_scaffold(out_path: Path) -> Path:
    """Emit a Fugaku/PJSUB scaffold (comment-only) for user adaptation.

    Tested in the POC on Fugaku; abmptools does not run integration
    tests for HPC schedulers. The user must edit the directives to
    match their group/queue/runtime budget.
    """
    text = dedent("""\
        #!/usr/bin/env bash
        # Auto-generated PJSUB scaffold (Fugaku). NOT tested by
        # abmptools; copy and adapt to your site's queue.
        # Replace the directives + body as needed.
        #
        ##PJM -L rscunit=rscunit_ft01
        ##PJM -L node=8
        ##PJM -L elapse=12:00:00
        ##PJM --mpi proc=8
        #
        # spack load /<your-genesis-version>
        # cd $PJM_O_WORKDIR
        # bash run.sh
        echo "PJSUB scaffold not implemented; see run.sh for the body."
        """)
    write_text(out_path, text)
    out_path.chmod(0o644)
    return out_path


def write_sbatch_scaffold(out_path: Path) -> Path:
    """Emit a SLURM (sbatch) scaffold (comment-only) for user adaptation."""
    text = dedent("""\
        #!/usr/bin/env bash
        # Auto-generated SLURM scaffold. NOT tested by abmptools.
        #
        ##SBATCH --job-name=grest
        ##SBATCH --nodes=1
        ##SBATCH --ntasks=8
        ##SBATCH --cpus-per-task=2
        ##SBATCH --time=24:00:00
        #
        # module load genesis
        # cd $SLURM_SUBMIT_DIR
        # bash run.sh
        echo "SLURM scaffold not implemented; see run.sh for the body."
        """)
    write_text(out_path, text)
    out_path.chmod(0o644)
    return out_path


__all__ = [
    "write_run_script",
    "write_pjsub_scaffold",
    "write_sbatch_scaffold",
]
