# -*- coding: utf-8 -*-
"""
abmptools.genesis.grest.system_builder
--------------------------------------
Run ``tleap`` to produce AMBER ``prmtop``, ``coor`` (inpcrd), and a
reference PDB from a user-supplied protein PDB.

This is the very first stage of the gREST_SSCR pipeline. Subsequent
stages consume the produced files via :class:`SystemMetadata`
(box dimensions are extracted from the ``%FLAG BOX_DIMENSIONS`` block
of the prmtop here).

Why not reuse :mod:`abmptools.membrane.parameterize_amber` directly?
That module is wired to ``MembraneConfig`` (lipid + water + ions) and
includes lipid-bilayer-specific tleap directives. genesis.grest needs
a leaner protein-only tleap script, so we keep a dedicated builder.
The two could be unified later via a shared ``write_tleap_input``
helper; deferred until a third caller appears.
"""
from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

from ._subprocess import CommandError, run_command, write_text
from .models import GrestBuildConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------

@dataclass
class TleapBuildResult:
    """Files emitted by the tleap stage.

    Attributes
    ----------
    prmtop
        AMBER topology (``%VERSION  ... %FLAG TITLE ...``).
    coor
        AMBER inpcrd (used as both ``ambcrdfile`` and ``ambreffile``
        in the GENESIS minimisation stage).
    ref_pdb
        Reference PDB (savepdb output) -- handy for subsequent
        analysis (e.g. cpptraj's ``parm`` + ``trajin``).
    leap_log
        Combined stdout/stderr of the tleap run.
    box_size_A
        ``(x, y, z)`` Angstrom from prmtop ``BOX_DIMENSIONS`` flag.
    n_protein_residues
        Total non-solvent, non-ion residues counted from prmtop
        ``RESIDUE_LABEL`` block. Used by ``inp_writer`` to render the
        default ``rno:1-N and heavy`` posres group.
    """
    prmtop: Path
    coor: Path
    ref_pdb: Path
    leap_log: Path
    box_size_A: Tuple[float, float, float]
    n_protein_residues: int


# ---------------------------------------------------------------------------
# tleap script generation
# ---------------------------------------------------------------------------

def write_tleap_script(
    cfg: GrestBuildConfig,
    input_pdb: Path,
    prmtop: Path,
    coor: Path,
    ref_pdb: Path,
    out_path: Path,
) -> Path:
    """Render and write the tleap input script for the grest pipeline.

    Steps:

    1. ``source <ff_protein>``
    2. ``source <ff_water>``
    3. extra ``source`` lines from :attr:`GrestBuildConfig.ff_extra`
    4. ``system = loadpdb <input_pdb>``
    5. ``charge system`` (audit)
    6. ``solvateBox system TIP3PBOX <padding>`` if water FF is TIP3P;
       otherwise ``solvatebox system <BOX_NAME> <padding>``
    7. ``addions system Na+ 0`` / ``addions system Cl- 0`` if
       ``cfg.neutralize``
    8. extra ``addions`` for ``cfg.salt_concentration_M`` -- linear
       approximation: ``round(salt_M * V_water_nm^3 * 0.602)`` ions of
       each species (deferred to a later improvement; current default
       is 0 -> skipped, neutralisation alone)
    9. ``saveAmberParm system <prmtop> <coor>``
    10. ``savepdb system <ref_pdb>``
    """
    lines: List[str] = [
        "# Auto-generated by abmptools.genesis.grest.system_builder",
        f"source {cfg.ff_protein}",
        f"source {cfg.ff_water}",
    ]
    for extra in cfg.ff_extra:
        lines.append(f"source {extra}")

    lines += [
        f"system = loadpdb {input_pdb}",
        "charge system",
    ]

    box_name = "TIP3PBOX" if "tip3p" in cfg.ff_water.lower() else "TIP3PBOX"
    lines.append(
        f"solvateBox system {box_name} {cfg.solvatebox_padding_A:.2f}"
    )

    if cfg.neutralize:
        lines += [
            "addions system Na+ 0",
            "addions system Cl- 0",
        ]

    if cfg.salt_concentration_M > 0:
        # Future improvement: derive a precise ion count from the box
        # volume (charge system + leap.log volume read). For v1.20.0,
        # we simply emit a comment that this needs a manual override.
        lines.append(
            f"# salt_concentration_M = {cfg.salt_concentration_M} (manual: "
            "edit this script and add 'addions system Na+ N / Cl- N')"
        )

    lines += [
        f"saveAmberParm system {prmtop} {coor}",
        f"savepdb system {ref_pdb}",
        "quit",
        "",
    ]

    write_text(out_path, "\n".join(lines))
    return out_path


# ---------------------------------------------------------------------------
# tleap runner
# ---------------------------------------------------------------------------

def run_tleap(
    script: Path,
    workdir: Path,
    log_path: Path,
    tleap_path: str = "tleap",
) -> None:
    """Invoke tleap on the rendered script.

    Captures combined stdout+stderr to *log_path*. Raises
    :class:`CommandError` on non-zero exit.
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    cmd = [tleap_path, "-f", str(script)]
    logger.info("Running tleap: %s", " ".join(cmd))
    try:
        result = run_command(cmd, cwd=workdir, capture=True)
    finally:
        # Always persist whatever tleap printed; useful for debugging.
        pass
    log_text = (
        f"=== argv ===\n{' '.join(cmd)}\n\n"
        f"=== stdout ===\n{result.stdout or ''}\n"
        f"=== stderr ===\n{result.stderr or ''}\n"
        f"=== returncode ===\n{result.returncode}\n"
    )
    write_text(log_path, log_text)


# ---------------------------------------------------------------------------
# prmtop parser (BOX_DIMENSIONS + residue count)
# ---------------------------------------------------------------------------

_FLAG_RE = re.compile(r"^%FLAG\s+(\S+)\s*$")
_FORMAT_RE = re.compile(r"^%FORMAT\(.*\)\s*$")


def _read_flag_block(text: str, flag_name: str) -> List[str]:
    """Extract the data lines for a given ``%FLAG`` from a prmtop body.

    Returns the raw lines between the ``%FORMAT(...)`` header and the
    next ``%FLAG``. Empty list if the flag is absent.
    """
    lines = text.splitlines()
    idx = 0
    while idx < len(lines):
        m = _FLAG_RE.match(lines[idx])
        if m and m.group(1) == flag_name:
            # Next line should be %FORMAT(...).
            idx += 1
            while idx < len(lines) and not _FORMAT_RE.match(lines[idx]):
                idx += 1
            idx += 1  # skip the format line itself
            block: List[str] = []
            while idx < len(lines) and not lines[idx].startswith("%FLAG"):
                if lines[idx].startswith("%"):
                    break
                block.append(lines[idx])
                idx += 1
            return block
        idx += 1
    return []


def parse_box_dimensions(prmtop_text: str) -> Tuple[float, float, float]:
    """Read ``%FLAG BOX_DIMENSIONS`` and return ``(x, y, z)`` Angstrom.

    AMBER prmtop ``BOX_DIMENSIONS`` block is:
    ``BETA  BOX(1)  BOX(2)  BOX(3)`` (first value is the angle; the
    remaining three are the cell lengths in Angstrom).

    Raises
    ------
    ValueError
        If the flag is missing or unparseable. A non-periodic prmtop
        (no solvateBox in tleap) is the typical cause.
    """
    block = _read_flag_block(prmtop_text, "BOX_DIMENSIONS")
    if not block:
        raise ValueError(
            "prmtop has no BOX_DIMENSIONS flag. Did the tleap script "
            "include 'solvateBox'? genesis.grest requires a periodic "
            "system."
        )
    tokens: List[float] = []
    for line in block:
        for tok in line.split():
            try:
                tokens.append(float(tok))
            except ValueError:
                continue
    if len(tokens) < 4:
        raise ValueError(
            f"BOX_DIMENSIONS block parsed only {len(tokens)} numeric "
            f"tokens (expected 4: beta + 3 box lengths)."
        )
    # First token is beta angle (90 for orthorhombic); next three are cells.
    return (tokens[1], tokens[2], tokens[3])


def parse_n_protein_residues(prmtop_text: str) -> int:
    """Count residues in ``%FLAG RESIDUE_LABEL`` excluding solvent/ions.

    Solvent labels recognised: ``WAT``, ``HOH``, ``TP3``.
    Ion labels recognised: ``Na+``, ``Cl-``, ``K+``, ``Mg+``, ``Ca+``,
    ``F-``, ``Br-``, ``I-``, ``Li+``, ``Cs+``, ``Rb+``.

    Used to render the default ``rno:1-N and heavy`` posres group in
    the minimisation stage.
    """
    block = _read_flag_block(prmtop_text, "RESIDUE_LABEL")
    if not block:
        raise ValueError(
            "prmtop has no RESIDUE_LABEL flag; cannot count residues."
        )
    solvent = {"WAT", "HOH", "TP3", "TIP3", "T3P"}
    ions = {
        "Na+", "Cl-", "K+", "Mg+", "Ca+", "F-", "Br-", "I-",
        "Li+", "Cs+", "Rb+", "NA", "CL", "K", "MG", "CA",
    }
    skip = solvent | ions
    n_protein = 0
    # AMBER prmtop residue labels are %FORMAT(20a4) -- 4 chars each, 20 per line.
    for line in block:
        for i in range(0, len(line), 4):
            tok = line[i : i + 4].strip()
            if not tok:
                continue
            if tok in skip:
                continue
            n_protein += 1
    return n_protein


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------

def build_amber_system(
    cfg: GrestBuildConfig,
    workdir: Path,
    input_pdb: Optional[Path] = None,
) -> TleapBuildResult:
    """Run tleap and harvest prmtop/coor/box metadata.

    Parameters
    ----------
    cfg
        Validated :class:`GrestBuildConfig`.
    workdir
        Build directory (created if missing). Receives ``system.tleap``,
        ``system.prmtop``, ``system.coor``, ``system_ref.pdb``,
        ``system_tleap.log``.
    input_pdb
        Override the config's ``input_pdb`` (useful in testing).
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    pdb = Path(input_pdb) if input_pdb else Path(cfg.input_pdb)
    if not pdb.is_absolute():
        pdb = pdb.resolve()

    script = workdir / "system.tleap"
    prmtop = workdir / "system.prmtop"
    coor = workdir / "system.coor"
    ref_pdb = workdir / "system_ref.pdb"
    leap_log = workdir / "system_tleap.log"

    write_tleap_script(
        cfg=cfg,
        input_pdb=pdb,
        prmtop=prmtop,
        coor=coor,
        ref_pdb=ref_pdb,
        out_path=script,
    )
    run_tleap(
        script=script,
        workdir=workdir,
        log_path=leap_log,
        tleap_path=cfg.tleap_path,
    )

    if not prmtop.exists():
        raise CommandError(
            cmd=f"{cfg.tleap_path} -f {script}",
            returncode=1,
            stderr=(
                f"tleap completed but {prmtop} is missing. "
                f"Inspect {leap_log} for diagnostics."
            ),
        )

    prmtop_text = prmtop.read_text()
    box = parse_box_dimensions(prmtop_text)
    n_residues = parse_n_protein_residues(prmtop_text)

    return TleapBuildResult(
        prmtop=prmtop,
        coor=coor,
        ref_pdb=ref_pdb,
        leap_log=leap_log,
        box_size_A=box,
        n_protein_residues=n_residues,
    )


__all__ = [
    "TleapBuildResult",
    "build_amber_system",
    "parse_box_dimensions",
    "parse_n_protein_residues",
    "run_tleap",
    "write_tleap_script",
]
