# -*- coding: utf-8 -*-
"""
abmptools.cg.peptide.builder
-----------------------------
End-to-end Martini 3 peptide CG system builder.

6 stage pipeline (:meth:`PeptideCGBuilder.build`):

    1. atomistic peptide PDB (tleap or extended-backbone fallback)
    2. ``martinize2 -ff martini3001`` -> CG ITP / PDB
    3. ``gmx insert-molecules`` -> packed.gro
    4. ``gmx solvate`` -> system_solv.gro (Martini W)
    5. ``gmx grompp`` + ``gmx genion`` -> system_ions.gro (NaCl 中和 + 0.15 M)
    6. write MDP files + index.ndx + run.sh

Output layout (under :attr:`PeptideBuildConfig.output_dir`)::

    output_dir/
      config.json
      topol.top
      packed.gro
      system_solv.gro
      system_ions.gro
      ions.mdp
      ions.tpr
      index.ndx
      molecules/<name>/
        <name>_atomistic.pdb
        <name>_cg.pdb
        <name>.itp
      mdp/{em,nvt,npt,md}.mdp
      run/run.sh
"""
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import Any, Dict, List, Tuple

from . import (
    forcefield_check,
    martinize_runner,
    mdp_templates,
    peptide_atomistic,
    system_packer,
    top_writer,
    water_box,
)
from ._subprocess import ensure_dir, write_text
from .models import PeptideBuildConfig

logger = logging.getLogger(__name__)


RUN_SCRIPT_TEMPLATE = """\
#!/bin/bash
# Generated by abmptools.cg.peptide
# GROMACS run script for a Martini 3 peptide CG system.
#
# Usage: bash run/run.sh
set -euo pipefail
cd "$(dirname "$0")/.."

GMX="${{GMX:-{gmx}}}"

echo "[1/4] Energy minimization..."
$GMX grompp -f mdp/em.mdp  -c system_ions.gro -p topol.top -o em.tpr -maxwarn 5
$GMX mdrun  -deffnm em -v

echo "[2/4] NVT equilibration..."
$GMX grompp -f mdp/nvt.mdp -c em.gro -p topol.top -o nvt.tpr -maxwarn 5
$GMX mdrun  -deffnm nvt -v

echo "[3/4] NPT equilibration..."
$GMX grompp -f mdp/npt.mdp -c nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -maxwarn 5
$GMX mdrun  -deffnm npt -v

echo "[4/4] Production MD..."
$GMX grompp -f mdp/md.mdp  -c npt.gro -t npt.cpt -p topol.top -o md.tpr -maxwarn 5
$GMX mdrun  -deffnm md -v

echo "Done."
"""


class PeptideCGBuilder:
    """Build a Martini 3 peptide CG system from a :class:`PeptideBuildConfig`."""

    def __init__(self, config: PeptideBuildConfig):
        self.config = config
        self.output_dir = ensure_dir(Path(config.output_dir).resolve())
        self.molecules_dir = ensure_dir(self.output_dir / "molecules")
        self.mdp_dir = ensure_dir(self.output_dir / "mdp")
        self.run_dir = ensure_dir(self.output_dir / "run")
        self.itp_paths: Dict[str, Path] = {}
        self.cg_pdb_paths: Dict[str, Path] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build(self) -> Dict[str, Any]:
        """Run the full 6-stage pipeline. Returns a result dictionary."""
        if not self.config.peptides:
            raise ValueError("PeptideBuildConfig.peptides is empty")

        ff_dir = self._resolve_ff_dir()
        self._copy_ff_files(ff_dir)

        logger.info("=== Stage 1/6: atomistic PDB ===")
        self._stage1_atomistic()
        logger.info("=== Stage 2/6: martinize2 (Martini 3 CG) ===")
        self._stage2_martinize2()
        logger.info("=== Stage 3/6: pack peptides into box ===")
        packed_gro = self._stage3_pack()

        # Topology must exist before solvate (gmx writes solvent count to it)
        topol_top = self._write_topology()

        if self.config.solvent_enabled:
            logger.info("=== Stage 4/6: gmx solvate ===")
            solvated_gro = self._stage4_solvate(packed_gro, topol_top, ff_dir)
            logger.info("=== Stage 5/6: gmx genion (NaCl) ===")
            packed_system = self._stage5_ions(solvated_gro, topol_top)
            final_gro = packed_system.ions_gro
        else:
            logger.info("=== Stage 4-5/6: skipped (solvent disabled) ===")
            final_gro = packed_gro

        logger.info("=== Stage 6/6: MDP + index + run.sh ===")
        ndx, mdp_files, run_script = self._stage6_outputs(final_gro)

        config_json = self.output_dir / "config.json"
        self.config.to_json(str(config_json))

        result: Dict[str, Any] = {
            "output_dir": self.output_dir,
            "gro": final_gro,
            "top": topol_top,
            "ndx": ndx,
            "mdp_files": mdp_files,
            "run_script": run_script,
            "config_json": config_json,
            "n_peptides_total": sum(p.count for p in self.config.peptides),
        }
        if self.config.box_lengths_nm is not None:
            result["box_nm"] = tuple(self.config.box_lengths_nm)
        else:
            b = self.config.box_size_nm
            result["box_nm"] = (b, b, b)
        return result

    # ------------------------------------------------------------------
    # Stage helpers
    # ------------------------------------------------------------------

    def _stage1_atomistic(self) -> None:
        for spec in self.config.peptides:
            mol_dir = ensure_dir(self.molecules_dir / spec.name)
            peptide_atomistic.build_atomistic_pdb(
                spec.sequence, spec.name, mol_dir,
                tleap_path=self.config.tleap_path,
            )

    def _stage2_martinize2(self) -> None:
        for spec in self.config.peptides:
            mol_dir = self.molecules_dir / spec.name
            atomistic_pdb = mol_dir / f"{spec.name}_atomistic.pdb"
            itp, cg = martinize_runner.run_martinize2(
                atomistic_pdb, mol_dir, spec.name,
                martinize2_path=self.config.martinize2_path,
            )
            self.itp_paths[spec.name] = itp
            self.cg_pdb_paths[spec.name] = cg

    def _stage3_pack(self) -> Path:
        peptide_specs: List[Tuple[str, Path, int]] = [
            (spec.name, self.cg_pdb_paths[spec.name], spec.count)
            for spec in self.config.peptides
        ]
        return system_packer.insert_peptides(
            peptide_specs, self.output_dir,
            box_size_nm=self.config.box_size_nm,
            box_lengths_nm=self.config.box_lengths_nm,
            gmx_path=self.config.gmx_path,
            seed=self.config.seed,
        )

    def _stage4_solvate(
        self, packed_gro: Path, topol_top: Path, ff_dir: Path,
    ) -> Path:
        water_gro = ff_dir / "martini_v3.0.0_water.gro"
        if not water_gro.exists():
            logger.info(
                "martini_v3.0.0_water.gro not found in %s; "
                "auto-generating a Martini W box via gmx insert-molecules "
                "(cgmartini.nl does not distribute one directly)",
                ff_dir,
            )
            water_gro = water_box.make_martini_water_box(
                self.output_dir / "_auto_martini_w_box.gro",
                gmx_path=self.config.gmx_path,
            )
        return system_packer.solvate(
            packed_gro, topol_top, self.output_dir, water_gro,
            gmx_path=self.config.gmx_path,
        )

    def _stage5_ions(
        self, solvated_gro: Path, topol_top: Path,
    ) -> system_packer.PackedSystem:
        return system_packer.add_ions(
            solvated_gro, topol_top, self.output_dir,
            gmx_path=self.config.gmx_path,
            neutralize=self.config.neutralize,
            conc_molar=self.config.nacl_molar,
        )

    def _stage6_outputs(
        self, final_gro: Path,
    ) -> Tuple[Path, Dict[str, Path], Path]:
        ndx = system_packer.make_index(
            final_gro, self.output_dir, gmx_path=self.config.gmx_path,
        )
        mdp_files = mdp_templates.generate_mdp_files(self.config, self.mdp_dir)
        run_script = self.run_dir / "run.sh"
        write_text(
            run_script,
            RUN_SCRIPT_TEMPLATE.format(gmx=self.config.gmx_path),
        )
        run_script.chmod(0o755)
        return ndx, mdp_files, run_script

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _write_topology(self) -> Path:
        topol_top = self.output_dir / "topol.top"
        return top_writer.write_topol_top(
            self.config, self.itp_paths, topol_top,
        )

    def _resolve_ff_dir(self) -> Path:
        if self.config.martini_itp_dir:
            return Path(self.config.martini_itp_dir).resolve()
        return self.output_dir / "ff"

    def _copy_ff_files(self, ff_dir: Path) -> None:
        """Copy required Martini 3 ITP files into output_dir.

        ``topol.top`` uses bare-name ``#include "martini_v3.0.0.itp"``;
        ``gmx grompp`` resolves these relative to the topology's directory,
        so the ITP files must live alongside topol.top. We copy (not
        symlink) for portability with run scripts that may move the
        directory.
        """
        for fname in forcefield_check.REQUIRED_MARTINI_FILES:
            src = ff_dir / fname
            dst = self.output_dir / fname
            if src.exists():
                if dst.exists():
                    continue  # idempotent re-runs
                shutil.copy2(src, dst)
                logger.debug("Copied %s -> %s", src, dst)
            else:
                logger.warning(
                    "Required Martini 3 file %s not found in %s; "
                    "gmx grompp will fail without it",
                    fname, ff_dir,
                )
