# -*- coding: utf-8 -*-
"""
abmptools.cg.peptide.mdp_templates
-----------------------------------
Martini 3 MDP templates and writer.

Defaults: cutoff = 1.1 nm, reaction-field, dt = 20 fs, v-rescale
T-coupling, c-rescale P-coupling. Configurable via
:class:`~abmptools.cg.peptide.models.PeptideBuildConfig`.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict

from ._subprocess import ensure_dir, write_text
from .models import PeptideBuildConfig

logger = logging.getLogger(__name__)


# Common nonbonded block (no format placeholders).
_NB_BLOCK = """\
; Neighbour list
nstlist         = 10
cutoff-scheme   = Verlet
ns_type         = grid
pbc             = xyz
verlet-buffer-tolerance = 0.005

; Electrostatics
coulombtype     = reaction-field
rcoulomb        = 1.1
epsilon_r       = 15
epsilon_rf      = 0

; Van der Waals
vdwtype         = cutoff
rvdw            = 1.1
vdw-modifier    = Potential-shift-Verlet
"""

# Temperature coupling block (uses {ref_t}).
_TC_BLOCK = """\
; Temperature coupling
tcoupl      = v-rescale
tc-grps     = System
tau_t       = 1.0
ref_t       = {ref_t:.1f}
"""

# Pressure coupling block (no placeholders).
_PC_BLOCK = """\
; Pressure coupling
pcoupl          = c-rescale
pcoupltype      = isotropic
tau_p           = 12.0
ref_p           = 1.0
compressibility = 3e-4
"""


_EM_TEMPLATE = """\
; Energy minimization for Martini 3 CG system
; Generated by abmptools.cg.peptide

integrator  = steep
nsteps      = {em_steps}
emtol       = 1000.0
emstep      = 0.01

""" + _NB_BLOCK


_NVT_TEMPLATE = """\
; NVT equilibration for Martini 3 CG system
; Generated by abmptools.cg.peptide

integrator  = md
dt          = {dt_ps:.4f}
nsteps      = {nsteps}
nstxout     = 0
nstvout     = 0
nstfout     = 0
nstlog      = 1000
nstenergy   = 1000
nstxout-compressed = 5000
compressed-x-grps  = System

""" + _NB_BLOCK + "\n" + _TC_BLOCK + """
; No pressure coupling in NVT
pcoupl      = no

; Velocity generation
gen-vel     = yes
gen-temp    = {ref_t:.1f}
gen-seed    = -1

constraints = none
"""


_NPT_TEMPLATE = """\
; NPT equilibration for Martini 3 CG system
; Generated by abmptools.cg.peptide

integrator  = md
dt          = {dt_ps:.4f}
nsteps      = {nsteps}
nstxout     = 0
nstvout     = 0
nstfout     = 0
nstlog      = 1000
nstenergy   = 1000
nstxout-compressed = 5000
compressed-x-grps  = System

""" + _NB_BLOCK + "\n" + _TC_BLOCK + "\n" + _PC_BLOCK + """
gen-vel     = no

constraints = none
"""


_MD_TEMPLATE = """\
; Production MD for Martini 3 CG system
; Generated by abmptools.cg.peptide

integrator  = md
dt          = {dt_ps:.4f}
nsteps      = {nsteps}
nstxout     = 0
nstvout     = 0
nstfout     = 0
nstlog      = 5000
nstenergy   = 5000
nstxout-compressed = 5000
compressed-x-grps  = System

""" + _NB_BLOCK + "\n" + _TC_BLOCK + "\n" + _PC_BLOCK + """
gen-vel     = no

constraints = none
"""


def render_mdp(name: str, cfg: PeptideBuildConfig) -> str:
    """Render one MDP file content from a :class:`PeptideBuildConfig`."""
    dt_ps = cfg.dt_fs / 1000.0
    if name == "em":
        return _EM_TEMPLATE.format(em_steps=cfg.em_steps)
    if name == "nvt":
        return _NVT_TEMPLATE.format(
            dt_ps=dt_ps, nsteps=cfg.nvt_nsteps, ref_t=cfg.temperature,
        )
    if name == "npt":
        return _NPT_TEMPLATE.format(
            dt_ps=dt_ps, nsteps=cfg.npt_nsteps, ref_t=cfg.temperature,
        )
    if name == "md":
        return _MD_TEMPLATE.format(
            dt_ps=dt_ps, nsteps=cfg.md_nsteps, ref_t=cfg.temperature,
        )
    raise ValueError(f"Unknown MDP name: {name!r}")


def generate_mdp_files(
    cfg: PeptideBuildConfig, output_dir: Path,
) -> Dict[str, Path]:
    """Generate enabled MDP files and return ``{name: path}``."""
    output_dir = ensure_dir(Path(output_dir)).resolve()
    flags = {
        "em": cfg.mdp_em,
        "nvt": cfg.mdp_nvt,
        "npt": cfg.mdp_npt,
        "md": cfg.mdp_md,
    }
    out: Dict[str, Path] = {}
    for name, enabled in flags.items():
        if not enabled:
            continue
        path = output_dir / f"{name}.mdp"
        write_text(path, render_mdp(name, cfg))
        out[name] = path
    logger.info("Generated %d MDP file(s) in %s", len(out), output_dir)
    return out
