# -*- coding: utf-8 -*-
"""
abmptools.cg.peptide.top_writer
--------------------------------
Generate the system-level ``topol.top`` for a Martini 3 peptide build.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List

from ._subprocess import write_text
from .models import PeptideBuildConfig

logger = logging.getLogger(__name__)


M3_FF_INCLUDES = [
    "martini_v3.0.0.itp",
    "martini_v3.0.0_solvents_v1.itp",
    "martini_v3.0.0_ions_v1.itp",
]


def write_topol_top(
    config: PeptideBuildConfig,
    itp_paths: Dict[str, Path],
    output_path: Path,
) -> Path:
    """Write the system-level ``topol.top`` for Martini 3.

    Parameters
    ----------
    config
        Full build configuration.
    itp_paths
        Mapping of ``peptide name -> .itp file path``. Each itp is
        included via ``#include "molecules/<name>/<name>.itp"`` (relative
        to the topology directory).
    output_path
        Path to write ``topol.top``.

    Returns
    -------
    Path to the written file.
    """
    lines: List[str] = []
    lines.append("; Topology file generated by abmptools.cg.peptide")
    lines.append(";")
    lines.append("")
    lines.append("; --- Martini 3 force field includes ---")
    for inc in M3_FF_INCLUDES:
        lines.append(f'#include "{inc}"')
    lines.append("")
    lines.append("; --- Molecule (peptide) topologies ---")
    for spec in config.peptides:
        if spec.name in itp_paths:
            itp_rel = itp_paths[spec.name].name
            lines.append(f'#include "molecules/{spec.name}/{itp_rel}"')
    lines.append("")
    lines.append("[ system ]")
    lines.append("Martini 3 peptide system")
    lines.append("")
    lines.append("[ molecules ]")
    lines.append("; name  number")
    for spec in config.peptides:
        if spec.name in itp_paths:
            mol_name = _get_molecule_name_from_itp(itp_paths[spec.name])
            lines.append(f"{mol_name}  {spec.count}")
    if config.solvent_enabled:
        lines.append(
            "; Solvent W and ions (NA / CL) are appended below by "
            "gmx solvate / genion at runtime."
        )
    lines.append("")
    write_text(output_path, "\n".join(lines))
    logger.info("Wrote topology: %s", output_path)
    return output_path


def _get_molecule_name_from_itp(itp_path: Path) -> str:
    """Extract the molecule name from an ``.itp`` ``[ moleculetype ]`` section."""
    if not itp_path.exists():
        return "molecule"
    in_moleculetype = False
    with open(itp_path) as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("[ moleculetype ]") \
                    or stripped.startswith("[moleculetype]"):
                in_moleculetype = True
                continue
            if in_moleculetype:
                if stripped.startswith(";") or stripped == "":
                    continue
                if stripped.startswith("["):
                    break
                parts = stripped.split()
                if parts:
                    return parts[0]
    return "molecule"
