# -*- coding: utf-8 -*-
"""
abmptools.cg.membrane.umbrella
-------------------------------
Per-window MDP and run-script generation for CG umbrella sampling.

For each window i ∈ [0, n_windows), write
``windows/win_{i:03d}/window.mdp`` with a static pull-coord
(``pull-coord1-rate = 0``) at ``z_min + i * dz``. The actual MD
invocation (``gmx grompp`` + ``gmx mdrun``) is encoded in ``run.sh``
written by :func:`write_run_script`.
"""
from __future__ import annotations

import logging
import os
import stat
from pathlib import Path
from typing import Dict, Optional

from . import mdp_templates
from ._subprocess import ensure_dir
from .models import MembraneCGBuildConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Per-window MDP
# ---------------------------------------------------------------------------

def write_window_mdps(
    *, config: MembraneCGBuildConfig, windows_dir: Path,
    pbc_atom_g1: Optional[int] = None,
    pbc_atom_g2: Optional[int] = None,
) -> Dict[int, Path]:
    """Write per-window MDPs (one per umbrella window).

    Each window MDP is the NPT-semiisotropic CG template + a pull block
    with ``rate=0`` and ``init = z_min + i * dz``.

    Parameters
    ----------
    pbc_atom_g1
        Bilayer group's PBC reference atom (1-based). Required when the
        Bilayer diameter exceeds half the shortest box vector;
        compute with :func:`pulling.find_pbc_center_atom`.
    pbc_atom_g2
        Peptide group's PBC reference atom (1-based). Usually unnecessary.

    Returns
    -------
    dict
        Mapping window index → absolute path to that window's MDP.
    """
    wd = ensure_dir(Path(windows_dir)).resolve()

    u = config.umbrella
    out: Dict[int, Path] = {}
    for i in range(u.n_windows):
        z_target = u.z_min_nm + i * u.window_spacing_nm
        win_dir = wd / f"win_{i:03d}"
        win_dir.mkdir(parents=True, exist_ok=True)

        text = mdp_templates.render_window_mdp(
            config=config,
            window_z_nm=z_target,
            pbc_atom_g1=pbc_atom_g1,
            pbc_atom_g2=pbc_atom_g2,
        )
        # Add a header line for human readability.
        text = (
            f"; window {i:03d}.mdp -- static umbrella at z = {z_target:+.3f} nm\n"
            "; (NPT-semiisotropic CG chassis + static pull-code block)\n\n"
            + text
        )
        mdp_path = win_dir / "window.mdp"
        mdp_path.write_text(text)
        out[i] = mdp_path

    logger.info("wrote %d window MDPs in %s", len(out), wd)
    return out


# ---------------------------------------------------------------------------
# Run script (bash)
# ---------------------------------------------------------------------------

def write_run_script(
    *, config: MembraneCGBuildConfig,
    top: Path, gro: Path, ndx: Path,
    equil_mdps: Dict[str, Path],
    pull_mdp: Path,
    window_mdps: Dict[int, Path],
    output_dir: Path,
) -> Path:
    """Write the top-level POSIX bash run script for the CG membrane US flow.

    The script encodes:

      1. em → nvt → npt equilibration (sequential)
      2. pulling MD (uses npt.gro as input)
      3. ``python -m abmptools.cg.membrane make-windows`` → extract window
         starting frames from pull.xtc
      4. per-window grompp + mdrun (sequential — replace with GNU parallel
         or job-array for HPC)
      5. ``python -m abmptools.cg.membrane wham`` → ``gmx wham`` + plots

    Returns the absolute path to ``run.sh``.
    """
    out_dir = Path(output_dir).resolve()
    script_path = out_dir / "run.sh"

    def rel(p: Path) -> str:
        return os.path.relpath(str(p), str(out_dir))

    em_mdp = rel(equil_mdps["em"])
    nvt_mdp = rel(equil_mdps["nvt"])
    npt_mdp = rel(equil_mdps["npt"])
    pull_mdp_rel = rel(pull_mdp)
    top_rel = rel(top)
    gro_rel = rel(gro)
    ndx_rel = rel(ndx)

    n_windows = len(window_mdps)

    content = f"""#!/usr/bin/env bash
# Auto-generated by abmptools.cg.membrane.umbrella.write_run_script.
# Edit GMX/NT/MPI variables to match your cluster, then run from {out_dir}.
set -euo pipefail
cd "$(dirname "$0")"

# --- tool paths (override via env if needed) ---
GMX="${{GMX:-{config.gmx_path}}}"
NT="${{NT:-4}}"            # total threads (single-rank OpenMP)
export OMP_NUM_THREADS="$NT"

# --- mdrun extra options (CG benefits modestly from GPU offload) ---
# Default empty (CPU). For Martini, GPU offload of nonbonded helps; PME
# is not used (reaction-field), so -pme gpu is irrelevant.
#     MDRUN_OPTS="-nb gpu" bash run.sh
MDRUN_OPTS="${{MDRUN_OPTS:-}}"

GROMPP_MAXWARN="${{GROMPP_MAXWARN:-{config.grompp_maxwarn}}}"

# --- file paths (relative to this script) ---
TOP="{top_rel}"
GRO0="{gro_rel}"           # initial structure (post-insane + topology compose)
NDX="{ndx_rel}"

# ---------- Stage 1: energy minimisation ----------
mkdir -p equil
"$GMX" grompp -f {em_mdp} -p "$TOP" -c "$GRO0" -n "$NDX" \\
    -o equil/em.tpr -po equil/em.mdp_out -maxwarn "$GROMPP_MAXWARN"
"$GMX" mdrun -deffnm equil/em -ntmpi 1 -ntomp "$NT"

# ---------- Stage 2: NVT ----------
"$GMX" grompp -f {nvt_mdp} -p "$TOP" -c equil/em.gro -n "$NDX" \\
    -o equil/nvt.tpr -po equil/nvt.mdp_out -maxwarn "$GROMPP_MAXWARN"
"$GMX" mdrun -deffnm equil/nvt -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

# ---------- Stage 3: NPT-semiisotropic ----------
"$GMX" grompp -f {npt_mdp} -p "$TOP" -c equil/nvt.gro -n "$NDX" \\
    -o equil/npt.tpr -po equil/npt.mdp_out -maxwarn "$GROMPP_MAXWARN"
"$GMX" mdrun -deffnm equil/npt -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS

# ---------- Stage 4: pulling (steered MD along z) ----------
mkdir -p pull
"$GMX" grompp -f {pull_mdp_rel} -p "$TOP" -c equil/npt.gro -n "$NDX" \\
    -o pull/pull.tpr -po pull/pull.mdp_out -maxwarn "$GROMPP_MAXWARN"
"$GMX" mdrun -deffnm pull/pull -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS \\
    -px pull/pullx.xvg -pf pull/pullf.xvg

# ---------- Stage 5: extract per-window starting frames ----------
python -m abmptools.cg.membrane make-windows \\
    --pull-tpr pull/pull.tpr --pull-xtc pull/pull.xtc \\
    --pull-xvg pull/pullx.xvg \\
    --config input/config.json \\
    --windows-dir windows \\
    --gmx-path "$GMX"

# ---------- Stage 6: per-window MD ----------
for i in $(seq -f '%03g' 0 {n_windows - 1}); do
    WIN="windows/win_$i"
    "$GMX" grompp -f "$WIN/window.mdp" -p "$TOP" -c "$WIN/start.gro" \\
        -n "$NDX" -o "$WIN/window.tpr" -po "$WIN/window.mdp_out" \\
        -maxwarn "$GROMPP_MAXWARN"
    "$GMX" mdrun -deffnm "$WIN/window" -ntmpi 1 -ntomp "$NT" $MDRUN_OPTS \\
        -px "$WIN/pullx.xvg" -pf "$WIN/pullf.xvg"
done

# ---------- Stage 7: PMF analysis ----------
python -m abmptools.cg.membrane wham \\
    --windows-dir windows \\
    --config input/config.json \\
    --analysis-dir analysis \\
    --gmx-path "$GMX"

echo "=== run.sh complete ==="
"""
    script_path.write_text(content)
    st = os.stat(script_path)
    os.chmod(
        script_path,
        st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH,
    )
    return script_path
