# -*- coding: utf-8 -*-
"""
abmptools.fragmenter.cg_segmenter.dpdgen_exporter
-------------------------------------------------
CG segments から DPDgen 入力 (`{name}_monomer` + `{name}_calc_sett`) を生成する。

DPDgen は Koji Okuwaki 作の DPD UDF 生成ツール (OCTA COGNAC エコシステム、
FCEWS / ABINIT-MP / COGNAC と連携) で、CG セグメント間 bond と物理パラメータを
Python スクリプト形式で記述する。

## bond 距離・剛性ルール (本 exporter の default)

DPD の均等配置ではセグメント間距離は 0.86 が標準。ring-ring の結合は
cholesterol 流儀で 0.60 (特例) を採用する:

| bond 種類 | distance | stiffness |
|---|---|---|
| **ring-ring** (両端が ring / ring_with_substituent kind) | **0.60** | 200 |
| その他 (chain-chain、chain-ring 等) | **0.86** | 50 |

bond13_180 / bond13_120 等の higher-order bond は化学的判断が必要なので、
本 exporter は **bond12 (直接結合) のみ自動生成** し、higher-order はユーザーが
monomer file を手動編集する設計とする。

## 出力

```
output_dir/
├── {name}_monomer       # Python: bond12 = [...], bond12h = [[type, i, j, d, s, 0], ...]
└── {name}_calc_sett     # Python: total_num_list, step_list, phys_param, ratio_list, ...
```

## 既存 DPDgen sample との互換性

`/home/okuwaki/repos/dpdgen/sample/monomer_model/` 配下の各 sample
(cholesterol_mem / lipid_membrane / peptide-mem / protein / nafion / rubber /
ssPalm) と同じフォーマットで出力するため、`python makeudf_dpd.py -p
{name}_calc_sett` でそのまま使える。
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, List, Tuple

from .models import Segment

logger = logging.getLogger(__name__)

# Default DPD bond parameters
DPD_DEFAULT_DIST = 0.86          # DPD 均等配置時のセグメント間距離
DPD_RING_RING_DIST = 0.60        # ring-ring (cholesterol 特例、後で調整可)
DPD_DEFAULT_STIFFNESS = 50       # chain / mixed の default
DPD_RING_STIFFNESS = 200         # ring-ring (cholesterol 流儀)


DEFAULT_CALC_SETT_TEMPLATE = """\
# DPDgen calc_sett (generated by abmptools.fragmenter.cg_segmenter)
# TODO: edit aij_file path / ratio_list / phys_param to suit your system.

total_num_list = [{total_num}]
step_list = [{step}]
dump_ene = 0
dump = 0
density = 3.0
dt = 0.05
random = '.true.'
aij_file = '{aij_file}'
monomer_file = '{monomer_file}'

# in percent unit, XX = 100 - sum(monomer_ratio)
# TODO: edit per your system composition
ratio_list = [{{'{monomer_name}': 'solvent'}}]
name_tail_list = ['_dpdgen_from_cg']

default_file = {{
    'filename': 'zz_test.inp',
    'init_pos_file': 'pos.d', 'init_vel_file': 'vel.d',
    'aij_file': 'zz_aij.dat', 'particle_file': 'zz_part.dat',
    'bond_file': 'zz_bond.dat',
    'xyz_file': '00_traj.xyz', 'ene_file': '01_energy.dat',
    'vel_file': '02_vel.dat', 'pos_file': '03_pos.dat',
    'input_dump_file': '04_input_dump.dat',
}}

phys_param = {{
    'x': {bx}, 'y': {by}, 'z': {bz},
    'dt': dt, 'kb': 1.0, 'temperature': 1.0,
    'lambda': 0.65, 'rand_seed': 5489,
    'gamma': 6.7, 'cutoff': 1.0,
    'use_random_initial_coord': random,
}}
"""


def export_dpdgen(
    segments: List[Segment],
    mol: Any,
    output_dir: str,
    monomer_name: str = "cg",
    box_size: Tuple[float, float, float] = (10.0, 10.0, 10.0),
    total_num: int = 100000,
    step: int = 100,
    aij_file: str = "aij.dat",
) -> Tuple[Path, Path]:
    """CG segments から DPDgen 入力 2 ファイルを生成する。

    Parameters
    ----------
    segments
        CG segments (`atom_indices` が埋まっていること; cap は不要)。
    mol
        元 RDKit Mol (segment 間の atom 結合判定に使う)。
    output_dir
        出力ディレクトリ。なければ作成。
    monomer_name
        出力ファイル名のプレフィックス (`{name}_monomer` / `{name}_calc_sett`)。
    box_size
        calc_sett `phys_param` の (x, y, z) box サイズ (DPD 単位)。
    total_num
        calc_sett `total_num_list[0]` の total particle 数。
    step
        calc_sett `step_list[0]` の MD ステップ数。
    aij_file
        calc_sett に書き込む `aij_file` パス (aij.dat 自体は本 exporter では生成しない;
        ユーザーが別途 `fcews-manybody` 等で計算して配置する想定)。

    Returns
    -------
    (monomer_path, calc_sett_path)
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    bond12_pairs, bond12h_list = _compute_dpd_bonds(segments, mol)

    monomer_path = out / f"{monomer_name}_monomer"
    monomer_path.write_text(
        _format_monomer_file(bond12_pairs, bond12h_list, len(segments))
    )

    calc_sett_path = out / f"{monomer_name}_calc_sett"
    calc_sett_path.write_text(
        DEFAULT_CALC_SETT_TEMPLATE.format(
            total_num=total_num,
            step=step,
            aij_file=aij_file,
            monomer_file=monomer_path.name,
            monomer_name=monomer_name,
            bx=box_size[0], by=box_size[1], bz=box_size[2],
        )
    )

    logger.info(
        "export_dpdgen: %d segments, %d bond12 pair(s) -> %s",
        len(segments), len(bond12_pairs), out,
    )
    return monomer_path, calc_sett_path


def _compute_dpd_bonds(
    segments: List[Segment],
    mol: Any,
) -> Tuple[List[List[int]], List[List]]:
    """セグメント間の bond12 を推定する。

    Rules
    -----
    - 2 segments が atom を **共有** (fused ring) → bond12 に追加
    - 共有 atom はないが、それぞれの atom 間に **直接 bond** がある (cap 経由 /
      ring-chain 境界) → bond12 に追加
    - distance / stiffness:
      - 両 segment の kind が "ring*" → 0.60 / stiff 200 (ring-ring 特例)
      - その他 → 0.86 / stiff 50 (DPD 均等配置 default)

    Returns
    -------
    bond12_pairs : List of [i, j] (segment_id ペア)
    bond12h_list : List of [type, i, j, distance, stiffness, 0]
    """
    bond12_pairs: List[List[int]] = []
    bond12h_list: List[List] = []

    seg_ids = sorted(s.segment_id for s in segments)
    seg_by_id = {s.segment_id: s for s in segments}

    for idx_i, i in enumerate(seg_ids):
        seg_i = seg_by_id[i]
        atoms_i = set(seg_i.atom_indices)
        for j in seg_ids[idx_i + 1:]:
            seg_j = seg_by_id[j]
            atoms_j = set(seg_j.atom_indices)

            has_shared = bool(atoms_i & atoms_j)
            has_direct = False
            if not has_shared:
                for a_i in atoms_i:
                    if has_direct:
                        break
                    for a_j in atoms_j:
                        if mol.GetBondBetweenAtoms(a_i, a_j) is not None:
                            has_direct = True
                            break

            if not (has_shared or has_direct):
                continue

            bond12_pairs.append([i, j])

            both_ring = (
                seg_i.kind.startswith("ring") and seg_j.kind.startswith("ring")
            )
            if both_ring:
                dist = DPD_RING_RING_DIST
                stiff = DPD_RING_STIFFNESS
            else:
                dist = DPD_DEFAULT_DIST
                stiff = DPD_DEFAULT_STIFFNESS
            bond12h_list.append([1, i, j, dist, stiff, 0])

    return bond12_pairs, bond12h_list


def _format_monomer_file(
    bond12_pairs: List[List[int]],
    bond12h_list: List[List],
    n_segments: int,
) -> str:
    """monomer file (Python script) の文字列を組み立てる。"""
    lines: List[str] = [
        "# DPDgen monomer definition (generated by abmptools.fragmenter.cg_segmenter)",
        f"# Particles: {n_segments} CG segments (idx = segment_id)",
        "#",
        "# Default bond distance: 0.86 (DPD uniform spacing)",
        "# Ring-ring bond distance: 0.60 (cholesterol-like special case;",
        "#                                 generated when both segments are ring*)",
        "# Stiffness: ring-ring = 200, chain/mixed = 50",
        "#",
        "# Higher-order bonds (bond13_180 / bond13_120 / ...) are NOT auto-generated.",
        "# Add manually after reviewing geometry.",
        "",
        f"bond12 = {_format_pairs(bond12_pairs)}",
        "",
        "# Per-bond detailed list [type, particle_i, particle_j, distance, stiffness, 0]",
        "bond12h = [",
    ]
    for b in bond12h_list:
        lines.append(f"    [{b[0]}, {b[1]}, {b[2]}, {b[3]}, {b[4]}, {b[5]}],")
    lines.append("]")
    lines.append("")
    lines.append("# Uncomment and fill manually for higher-order bonds:")
    lines.append("# bond13_180 = []     # 1-3 linear (e.g. consecutive ring atoms, dist 1.72)")
    lines.append("# bond13_120 = []     # 1-3 cis double bond (dist 1.49)")
    lines.append("")
    return "\n".join(lines)


def _format_pairs(pairs: List[List[int]]) -> str:
    """`[[i, j], [i, j], ...]` を 1 行で読みやすく整形。"""
    if not pairs:
        return "[]"
    return "[" + ", ".join(f"[{p[0]}, {p[1]}]" for p in pairs) + "]"
