# -*- coding: utf-8 -*-
"""
abmptools.fragmenter.cg_segmenter.dpdgen_exporter
-------------------------------------------------
CG segments から DPDgen 入力 (`{name}_monomer` + `{name}_calc_sett`) を生成する。

DPDgen は Koji Okuwaki 作の DPD UDF 生成ツール (OCTA COGNAC エコシステム、
FCEWS / ABINIT-MP / COGNAC と連携)。CG セグメント間 bond と物理パラメータを
Python スクリプト形式で記述する。

## 生成される 5 種類の constraint

### bond ポテンシャル (距離制約) — `bondNN = [[i, j], ...]` + `bondNNh = [[type, i, j, dist, stiff, 0], ...]`

| 種類 | 検出 | distance | stiffness |
|---|---|---|---|
| **bond12** (隣接 path 1) | 共有 atom or 直接 atom bond | 0.86 / 0.60 (ring-ring) | 50 / 200 |
| **bond13_150** (1-skip ring, 新) | fused ring chain BFS path 2 | **1.661** (cosine law, 150° 想定) | 200 |
| **bond14_150** (2-skip ring, 新) | fused ring chain BFS path 3 | **2.502** (4-ring chain extension) | 200 |

### angle ポテンシャル (角度制約) — `angle13 = [[a, b, c], ...]` + `angle13data = [[a, b, c, eq_余角, stiff], ...]`

cognac 流儀: **平衡角は余角** (180° - θ) で指定。stiffness = 5.0 一律。

| 種類 | 検出 | eq (余角) |
|---|---|---|
| 両端 ring + 中央 ring | bond12 graph path 2 (3 segments すべて ring) | **30** (= 150°) |
| cis 二重結合 | mol `BondType.DOUBLE` 周辺の 3 segment | **60** (= 120°) |
| その他 (chain / mixed) | bond12 graph path 2 (上記以外) | **0** (= 180° 直線想定) |

### オプション (コメントアウト template)

`bond13_180h` (dist 1.72) / `bond13_120h` (dist 1.49) は **angle ポテンシャルで十分**
として default では生成しない。距離制約も併用したい場合は monomer file の
コメントアウト template を uncomment する。

## 出力

```
output_dir/
├── {name}_monomer       # Python script (上記 5 種類)
└── {name}_calc_sett     # Python: total_num_list, step_list, phys_param, ...
```

## 既存 DPDgen sample との互換性

`/home/okuwaki/repos/dpdgen/sample/monomer_model/membrane_angleon/` の
angle13 / angle13data format に準拠。`python makeudf_dpd.py -p {name}_calc_sett`
でそのまま処理できる。
"""
from __future__ import annotations

import logging
from collections import deque
from pathlib import Path
from typing import Any, List, Tuple

from .models import Segment

logger = logging.getLogger(__name__)

# --- bond ポテンシャル defaults ---
DPD_DEFAULT_DIST = 0.86          # DPD 均等配置時のセグメント間距離
DPD_RING_RING_DIST = 0.60        # ring-ring (cholesterol 特例)
DPD_DEFAULT_STIFFNESS = 50       # chain / mixed の default
DPD_RING_STIFFNESS = 200         # ring-ring (cholesterol 流儀)

# Ring chain hierarchical distance constraint (cholesterol-like A-B-C-D fused)
DPD_BOND13_150_DIST = 1.661      # 1-skip ring (余弦定理, 150° 想定)
DPD_BOND14_150_DIST = 2.502      # 2-skip ring (4-ring chain extension)
DPD_RING_CHAIN_BOND_STIFFNESS = 200

# --- angle ポテンシャル defaults (cognac 余角 convention, stiffness 5.0) ---
DPD_ANGLE_EQ_RING_BEND = 30      # 150° → 余角 30
DPD_ANGLE_EQ_CHAIN_LINEAR = 0    # 180° → 余角 0 (直線想定)
DPD_ANGLE_EQ_CIS_DOUBLE = 60     # 120° → 余角 60
DPD_ANGLE_STIFFNESS = 5.0

# --- 旧 bond13 距離制約 defaults (オプション、 default 出力しない) ---
DPD_BOND13_180_DIST = 1.72
DPD_BOND13_180_RING_STIFFNESS = 200
DPD_BOND13_180_CHAIN_STIFFNESS = 80
DPD_BOND13_120_DIST = 1.49
DPD_BOND13_120_STIFFNESS = 70


DEFAULT_CALC_SETT_TEMPLATE = """\
# DPDgen calc_sett (generated by abmptools.fragmenter.cg_segmenter)
# TODO: edit aij_file path / ratio_list / phys_param to suit your system.

total_num_list = [{total_num}]
step_list = [{step}]
dump_ene = 0
dump = 0
density = 3.0
dt = 0.05
random = '.true.'
aij_file = '{aij_file}'
monomer_file = '{monomer_file}'

# in percent unit, XX = 100 - sum(monomer_ratio)
# TODO: edit per your system composition
ratio_list = [{{'{monomer_name}': 'solvent'}}]
name_tail_list = ['_dpdgen_from_cg']

default_file = {{
    'filename': 'zz_test.inp',
    'init_pos_file': 'pos.d', 'init_vel_file': 'vel.d',
    'aij_file': 'zz_aij.dat', 'particle_file': 'zz_part.dat',
    'bond_file': 'zz_bond.dat',
    'xyz_file': '00_traj.xyz', 'ene_file': '01_energy.dat',
    'vel_file': '02_vel.dat', 'pos_file': '03_pos.dat',
    'input_dump_file': '04_input_dump.dat',
}}

phys_param = {{
    'x': {bx}, 'y': {by}, 'z': {bz},
    'dt': dt, 'kb': 1.0, 'temperature': 1.0,
    'lambda': 0.65, 'rand_seed': 5489,
    'gamma': 6.7, 'cutoff': 1.0,
    'use_random_initial_coord': random,
}}
"""


def export_dpdgen(
    segments: List[Segment],
    mol: Any,
    output_dir: str,
    monomer_name: str = "cg",
    box_size: Tuple[float, float, float] = (10.0, 10.0, 10.0),
    total_num: int = 100000,
    step: int = 100,
    aij_file: str = "aij.dat",
) -> Tuple[Path, Path]:
    """CG segments から DPDgen 入力 2 ファイルを生成する。

    Parameters
    ----------
    segments
        CG segments (`atom_indices` が埋まっていること; cap は不要)。
    mol
        元 RDKit Mol (segment 間の atom 結合判定 + double bond 検出に使う)。
    output_dir
        出力ディレクトリ。なければ作成。
    monomer_name
        出力ファイル名のプレフィックス (`{name}_monomer` / `{name}_calc_sett`)。
    box_size
        calc_sett `phys_param` の (x, y, z) box サイズ (DPD 単位)。
    total_num, step
        calc_sett の MD 設定。
    aij_file
        calc_sett に書き込む `aij_file` パス (本 exporter では生成しない;
        ユーザーが別途 `fcews-manybody` 等で計算して配置する想定)。

    Returns
    -------
    (monomer_path, calc_sett_path)
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    bond12_pairs, bond12h_list = _compute_dpd_bonds(segments, mol)
    (bond13_150_pairs, bond13_150h_list,
     bond14_150_pairs, bond14_150h_list) = _compute_ring_chain_path_bonds(
        segments, bond12_pairs,
    )
    angle13_triples, angle13data_list = _compute_dpd_angles(
        segments, mol, bond12_pairs,
    )

    monomer_path = out / f"{monomer_name}_monomer"
    monomer_path.write_text(
        _format_monomer_file(
            bond12_pairs, bond12h_list,
            bond13_150_pairs, bond13_150h_list,
            bond14_150_pairs, bond14_150h_list,
            angle13_triples, angle13data_list,
            len(segments),
        )
    )

    calc_sett_path = out / f"{monomer_name}_calc_sett"
    calc_sett_path.write_text(
        DEFAULT_CALC_SETT_TEMPLATE.format(
            total_num=total_num,
            step=step,
            aij_file=aij_file,
            monomer_file=monomer_path.name,
            monomer_name=monomer_name,
            bx=box_size[0], by=box_size[1], bz=box_size[2],
        )
    )

    logger.info(
        "export_dpdgen: %d seg, bond12=%d / bond13_150=%d / bond14_150=%d / angle13=%d -> %s",
        len(segments),
        len(bond12_pairs), len(bond13_150_pairs),
        len(bond14_150_pairs), len(angle13_triples),
        out,
    )
    return monomer_path, calc_sett_path


def _compute_dpd_bonds(
    segments: List[Segment],
    mol: Any,
) -> Tuple[List[List[int]], List[List]]:
    """bond12 (path 1) のみ生成。 fused ring full-connect は **行わない**
    (A-D 等の長距離 ring pair は bond14_150 で扱う、本関数では出さない)。

    Rules
    -----
    - 共有 atom (fused ring boundary) があれば bond12
    - 直接 atom bond (cap 経由 / ring-chain 境界) があれば bond12
    - distance / stiffness:
      - 両 segment が "ring*" kind → 0.60 / stiff 200 (cholesterol 流儀)
      - その他 → 0.86 / stiff 50 (DPD 均等配置 default)
    """
    bond12_pairs: List[List[int]] = []
    bond12h_list: List[List] = []

    seg_by_id = {s.segment_id: s for s in segments}
    seg_ids = sorted(seg_by_id.keys())

    # boundary atom (= 複数 segment に shared assigned) を識別
    # has_direct check の際に boundary atom 経由の cross-ring bond を除外するため
    atom_seg_count: dict = {}
    for s in segments:
        for a in s.atom_indices:
            atom_seg_count[a] = atom_seg_count.get(a, 0) + 1

    def _is_unique_atom(a: int) -> bool:
        return atom_seg_count.get(a, 0) <= 1

    for idx_i, i in enumerate(seg_ids):
        seg_i = seg_by_id[i]
        atoms_i = set(seg_i.atom_indices)
        for j in seg_ids[idx_i + 1:]:
            seg_j = seg_by_id[j]
            atoms_j = set(seg_j.atom_indices)

            has_shared = bool(atoms_i & atoms_j)
            has_direct = False
            if not has_shared:
                # unique atom (= 単一 segment にのみ属する) のみで direct bond
                # を判定。boundary atom 経由の cross-ring bond は除外する
                # (e.g. cholesterol B 環内部の atom が A 環と C 環の boundary
                # に shared assigned されている場合、 B 内部 bond を A-C
                # の direct bond と誤検出するのを防ぐ)。
                for a_i in atoms_i:
                    if not _is_unique_atom(a_i):
                        continue
                    if has_direct:
                        break
                    for a_j in atoms_j:
                        if not _is_unique_atom(a_j):
                            continue
                        if mol.GetBondBetweenAtoms(a_i, a_j) is not None:
                            has_direct = True
                            break

            if not (has_shared or has_direct):
                continue

            both_ring = (
                seg_i.kind.startswith("ring") and seg_j.kind.startswith("ring")
            )
            if both_ring:
                dist = DPD_RING_RING_DIST
                stiff = DPD_RING_STIFFNESS
            else:
                dist = DPD_DEFAULT_DIST
                stiff = DPD_DEFAULT_STIFFNESS
            bond12_pairs.append([i, j])
            bond12h_list.append([1, i, j, dist, stiff, 0])

    return bond12_pairs, bond12h_list


def _compute_ring_chain_path_bonds(
    segments: List[Segment],
    bond12_pairs: List[List[int]],
) -> Tuple[List[List[int]], List[List], List[List[int]], List[List]]:
    """fused ring chain (= ring-only subgraph of bond12) を BFS。

    - path length 2 → **bond13_150** (1.661、 cholesterol-like 150° 余弦定理)
    - path length 3 → **bond14_150** (2.502、 4-ring chain で 150°/165° 展開)
    - stiffness 200

    cholesterol A-B-C-D 4 環の場合:
        bond13_150 = [[0,2], [1,3]]   (A-C, B-D)
        bond14_150 = [[0,3]]          (A-D)
    """
    seg_by_id = {s.segment_id: s for s in segments}
    ring_ids = [s.segment_id for s in segments if s.kind.startswith("ring")]
    bond12_set = {tuple(sorted(p)) for p in bond12_pairs}

    # ring-only subgraph
    g: dict = {sid: set() for sid in ring_ids}
    for (i, j) in bond12_set:
        if i in g and j in g:
            g[i].add(j)
            g[j].add(i)

    bond13_150_pairs: List[List[int]] = []
    bond14_150_pairs: List[List[int]] = []

    for start in sorted(ring_ids):
        dist = {start: 0}
        queue: deque = deque([start])
        while queue:
            curr = queue.popleft()
            for nb in g[curr]:
                if nb not in dist:
                    dist[nb] = dist[curr] + 1
                    queue.append(nb)
        for sid, d in dist.items():
            if sid <= start:
                continue
            if d == 2:
                bond13_150_pairs.append([start, sid])
            elif d == 3:
                bond14_150_pairs.append([start, sid])

    bond13_150h_list: List[List] = [
        [1, p[0], p[1], DPD_BOND13_150_DIST, DPD_RING_CHAIN_BOND_STIFFNESS, 0]
        for p in bond13_150_pairs
    ]
    bond14_150h_list: List[List] = [
        [1, p[0], p[1], DPD_BOND14_150_DIST, DPD_RING_CHAIN_BOND_STIFFNESS, 0]
        for p in bond14_150_pairs
    ]

    return (
        bond13_150_pairs, bond13_150h_list,
        bond14_150_pairs, bond14_150h_list,
    )


def _compute_dpd_angles(
    segments: List[Segment],
    mol: Any,
    bond12_pairs: List[List[int]],
) -> Tuple[List[List[int]], List[List]]:
    """bond12 graph で path-length-2 → angle (a, b, c) を生成。 b は中央 segment。

    Rules (cognac 余角 convention):
      - 両端 ring + 中央 ring → eq **30** (= 150°、 cholesterol-like ring bend)
      - cis 二重結合 周辺 → eq **60** (= 120°)
      - その他 (chain / mixed) → eq **0** (= 180° 直線想定)
      - stiffness 一律 **5.0**

    Returns
    -------
    angle13_triples : List of [a, b, c] (b は中央)
    angle13data_list : List of [a, b, c, eq_余角, stiffness]
    """
    seg_by_id = {s.segment_id: s for s in segments}
    bond12_set = {tuple(sorted(p)) for p in bond12_pairs}

    # bond12 graph (隣接リスト)
    g: dict = {sid: set() for sid in seg_by_id}
    for (i, j) in bond12_set:
        g[i].add(j)
        g[j].add(i)

    # 1. bond12 path-length-2 → デフォルト angle
    angle13_triples: List[List[int]] = []
    angle13data_list: List[List] = []
    seen: dict = {}    # key = (sorted_outer_pair, center) -> idx in list

    for b_mid in sorted(g):
        seg_b = seg_by_id[b_mid]
        neighbors = sorted(g[b_mid])
        for idx_a, a in enumerate(neighbors):
            for c in neighbors[idx_a + 1:]:
                key = (tuple(sorted([a, c])), b_mid)
                if key in seen:
                    continue
                seg_a = seg_by_id[a]
                seg_c = seg_by_id[c]
                all_ring = (
                    seg_a.kind.startswith("ring") and
                    seg_b.kind.startswith("ring") and
                    seg_c.kind.startswith("ring")
                )
                eq = (DPD_ANGLE_EQ_RING_BEND if all_ring
                      else DPD_ANGLE_EQ_CHAIN_LINEAR)
                angle13_triples.append([a, b_mid, c])
                angle13data_list.append(
                    [a, b_mid, c, eq, DPD_ANGLE_STIFFNESS]
                )
                seen[key] = len(angle13_triples) - 1

    # 2. mol double bond → 該当 angle entry の eq を 60 で上書き
    try:
        from rdkit import Chem
        double_type = Chem.BondType.DOUBLE
    except ImportError:
        return angle13_triples, angle13data_list

    atom_to_segs: dict = {}
    for s in segments:
        for a in s.atom_indices:
            atom_to_segs.setdefault(a, []).append(s.segment_id)

    for bond in mol.GetBonds():
        if bond.GetBondType() != double_type:
            continue
        a1 = bond.GetBeginAtomIdx()
        a2 = bond.GetEndAtomIdx()
        segs1 = atom_to_segs.get(a1, [])
        segs2 = atom_to_segs.get(a2, [])

        for s1 in segs1:
            for s2 in segs2:
                if s1 == s2:
                    continue
                if tuple(sorted([s1, s2])) not in bond12_set:
                    continue
                # a1 周辺の 1-3 (中央 = s1)
                for nb in mol.GetAtomWithIdx(a1).GetNeighbors():
                    if nb.GetIdx() == a2 or nb.GetAtomicNum() == 1:
                        continue
                    for s_n in atom_to_segs.get(nb.GetIdx(), []):
                        if s_n == s1 or s_n == s2:
                            continue
                        if tuple(sorted([s_n, s1])) not in bond12_set:
                            continue
                        key = (tuple(sorted([s_n, s2])), s1)
                        if key in seen:
                            idx = seen[key]
                            angle13data_list[idx][3] = DPD_ANGLE_EQ_CIS_DOUBLE
                # a2 周辺の 1-3 (中央 = s2)
                for nb in mol.GetAtomWithIdx(a2).GetNeighbors():
                    if nb.GetIdx() == a1 or nb.GetAtomicNum() == 1:
                        continue
                    for s_n in atom_to_segs.get(nb.GetIdx(), []):
                        if s_n == s1 or s_n == s2:
                            continue
                        if tuple(sorted([s_n, s2])) not in bond12_set:
                            continue
                        key = (tuple(sorted([s_n, s1])), s2)
                        if key in seen:
                            idx = seen[key]
                            angle13data_list[idx][3] = DPD_ANGLE_EQ_CIS_DOUBLE

    return angle13_triples, angle13data_list


def _format_monomer_file(
    bond12_pairs: List[List[int]],
    bond12h_list: List[List],
    bond13_150_pairs: List[List[int]],
    bond13_150h_list: List[List],
    bond14_150_pairs: List[List[int]],
    bond14_150h_list: List[List],
    angle13_triples: List[List[int]],
    angle13data_list: List[List],
    n_segments: int,
) -> str:
    """monomer file (Python script) の文字列を組み立てる。"""
    lines: List[str] = [
        "# DPDgen monomer definition (generated by abmptools.fragmenter.cg_segmenter)",
        f"# Particles: {n_segments} CG segments (idx = segment_id)",
        "#",
        "# === Distance constraints (bond ポテンシャル) ===",
        "#   bond12      (path 1):  ring-ring 0.60/stiff 200, other 0.86/stiff 50",
        "#   bond13_150  (1-skip ring): 1.661 / stiff 200  (cosine law, 150° 仮定)",
        "#   bond14_150  (2-skip ring): 2.502 / stiff 200  (4-ring chain, 150°/165°)",
        "#",
        "# === Angle constraints (angle ポテンシャル) ===",
        "#   angle13 / angle13data: bond12 graph path-2 で b=中央",
        "#   eq は cognac 流の **余角** (180° - θ) 指定、stiffness 一律 5.0",
        "#     両端 ring + 中央 ring:  eq=30   (= 150° ring bend)",
        "#     cis 二重結合 周辺:      eq=60   (= 120°)",
        "#     その他 (chain / mixed): eq=0    (= 180° 直線想定)",
        "",
        f"bond12 = {_format_pairs(bond12_pairs)}",
        "",
        "bond12h = [",
    ]
    for b in bond12h_list:
        lines.append(f"    [{b[0]}, {b[1]}, {b[2]}, {b[3]}, {b[4]}, {b[5]}],")
    lines.append("]")
    lines.append("")
    lines.append(f"bond13_150 = {_format_pairs(bond13_150_pairs)}")
    lines.append("")
    lines.append("bond13_150h = [")
    for b in bond13_150h_list:
        lines.append(f"    [{b[0]}, {b[1]}, {b[2]}, {b[3]}, {b[4]}, {b[5]}],")
    lines.append("]")
    lines.append("")
    lines.append(f"bond14_150 = {_format_pairs(bond14_150_pairs)}")
    lines.append("")
    lines.append("bond14_150h = [")
    for b in bond14_150h_list:
        lines.append(f"    [{b[0]}, {b[1]}, {b[2]}, {b[3]}, {b[4]}, {b[5]}],")
    lines.append("]")
    lines.append("")
    lines.append(f"angle13 = {_format_triples(angle13_triples)}")
    lines.append("")
    lines.append("angle13data = [")
    for a in angle13data_list:
        lines.append(f"    [{a[0]}, {a[1]}, {a[2]}, {a[3]}, {a[4]}],")
    lines.append("]")
    lines.append("")
    lines.append(
        "# === Optional: 1-3 distance constraint (bond ポテンシャル) ==="
    )
    lines.append(
        "# Uncomment if you want both distance + angle constraint for the same 1-3 pairs."
    )
    lines.append(
        "# Default values:  bond13_180 -> dist 1.72, bond13_120 -> dist 1.49"
    )
    lines.append("# bond13_180 = []")
    lines.append("# bond13_180h = []")
    lines.append("# bond13_120 = []")
    lines.append("# bond13_120h = []")
    lines.append("")
    return "\n".join(lines)


def _format_pairs(pairs: List[List[int]]) -> str:
    """`[[i, j], [i, j], ...]` を 1 行で読みやすく整形。"""
    if not pairs:
        return "[]"
    return "[" + ", ".join(f"[{p[0]}, {p[1]}]" for p in pairs) + "]"


def _format_triples(triples: List[List[int]]) -> str:
    """`[[a, b, c], ...]` を 1 行で整形。"""
    if not triples:
        return "[]"
    return "[" + ", ".join(f"[{t[0]}, {t[1]}, {t[2]}]" for t in triples) + "]"
